### ISSUE TITLE
Random Exception in ASGI application - AttributeError: 'coroutine' object has no attribute '_resource_closers'

### ISSUE THREAD

**Issue by kwongtn** [getsentry/sentry-python#2573] opened 2023-12-07 13:50 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.38.0

### Steps to Reproduce

Here is my sentry settings in django's `settings.py`. Just load any web page.
Python 3.12
Happens the same with Django 4.2.8, 5.0

```py
import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.strawberry import StrawberryIntegration

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", None),
    environment=ENVIRONMENT,
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(
            monitor_beat_tasks=True,
        ),
        StrawberryIntegration(
            async_execution=True,
        ),
        RedisIntegration(),
    ],
    send_default_pii=True,
    _experiments={
        "profiles_sample_rate": 1.0,
    },
    sample_rate=0.3,
)
```

Here's my repo
https://github.com/kwongtn/lift-rosak-backend

### Expected Result

No errors

### Actual Result

Here are the logs
```py
2023-12-07 21:36:17 [2023-12-07 21:36:17 +0800] [21] [ERROR] Exception in ASGI application
2023-12-07 21:36:17 Traceback (most recent call last):
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-12-07 21:36:17     result = await app(  # type: ignore[func-returns-value]
2023-12-07 21:36:17              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-12-07 21:36:17     return await self.app(scope, receive, send)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/asgi.py", line 80, in sentry_patched_asgi_handler
2023-12-07 21:36:17     return await middleware(scope, receive, send)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
2023-12-07 21:36:17     return await self._run_app(scope, receive, send, asgi_version=3)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 241, in _run_app
2023-12-07 21:36:17     raise exc from None
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 234, in _run_app
2023-12-07 21:36:17     return await self.app(
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 170, in __call__
2023-12-07 21:36:17     await self.handle(scope, receive, send)
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 209, in handle
2023-12-07 21:36:17     task.result()
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 192, in process_request
2023-12-07 21:36:17     response = await self.run_get_response(request)
2023-12-07 21:36:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 237, in run_get_response
2023-12-07 21:36:17     response = await self.get_response_async(request)
2023-12-07 21:36:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/asgi.py", line 111, in sentry_patched_get_response_async
2023-12-07 21:36:17     return await old_get_response_async(self, request)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 163, in get_response_async
2023-12-07 21:36:17     response._resource_closers.append(request.close)
2023-12-07 21:36:17     ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17 AttributeError: 'coroutine' object has no attribute '_resource_closers'
```
```py
2023-12-07 21:36:17 [2023-12-07 21:36:17 +0800] [21] [ERROR] Exception in ASGI application
2023-12-07 21:36:17 Traceback (most recent call last):
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-12-07 21:36:17     result = await app(  # type: ignore[func-returns-value]
2023-12-07 21:36:17              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-12-07 21:36:17     return await self.app(scope, receive, send)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/asgi.py", line 80, in sentry_patched_asgi_handler
2023-12-07 21:36:17     return await middleware(scope, receive, send)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
2023-12-07 21:36:17     return await self._run_app(scope, receive, send, asgi_version=3)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 241, in _run_app
2023-12-07 21:36:17     raise exc from None
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 234, in _run_app
2023-12-07 21:36:17     return await self.app(
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 170, in __call__
2023-12-07 21:36:17     await self.handle(scope, receive, send)
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 209, in handle
2023-12-07 21:36:17     task.result()
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 192, in process_request
2023-12-07 21:36:17     response = await self.run_get_response(request)
2023-12-07 21:36:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 237, in run_get_response
2023-12-07 21:36:17     response = await self.get_response_async(request)
2023-12-07 21:36:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/asgi.py", line 111, in sentry_patched_get_response_async
2023-12-07 21:36:17     return await old_get_response_async(self, request)
2023-12-07 21:36:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 163, in get_response_async
2023-12-07 21:36:17     response._resource_closers.append(request.close)
2023-12-07 21:36:17     ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-07 21:36:17 AttributeError: 'coroutine' object has no attribute '_resource_closers'
```

**Comment by sentrivana** [comment] 2023-12-07 15:52
Hey @kwongtn, thanks for reporting this, we will have a look. In the meantime, did you observe this while upgrading to 1.38.0 from an older SDK version where it had worked?

Unrelated sidenote: `profiles_sample_rate` is now a full-fledged SDK option, so you can use it directly and not via `_experiments`.

**Comment by kwongtn** [comment] 2023-12-08 02:15
I had tested with a few combinations.

What breaks:
- Django 5.0, Python 3.12, Sentry SDK 1.38.0 (This issue)
- Django 4.2.8, Python 3.12, Sentry SDK 1.38.0
- Django 5.0, Python 3.12, Sentry SDK 1.36.0
- Django 4.2.8, Python 3.12, Sentry SDK 1.38.0
- Django 4.2.8, Python 3.12, Sentry SDK 1.36.0

What works:
- Django 4.2.7, Python 3.11, Sentry SDK 1.36.0
- Django 4.2.7, Python 3.11, Sentry SDK 1.35.0

From the test matrices above, it seems that the issue is with python 3.12 🤔

**Comment by sentrivana** [comment] 2023-12-11 09:04
Thanks @kwongtn, this is very helpful!

Couldn't repro so far with my async Django setup on 3.12 so there's probably something specific going on with your setup that's triggering this.

Stupid question, but if you take Sentry SDK out of the equation, don't initialize it and run the app, can you load a page? Just to double check that it's not caused by another library/django app that's not 3.12 ready yet.

Otherwise the best way forward would be to find a minimal reproducible example -- does removing some `INSTALLED_APPS` or `MIDDLEWARE` from settings.py make the issue go away? Are there some views that work?

**Comment by kwongtn** [comment] 2023-12-17 18:57
> Stupid question, but if you take Sentry SDK out of the equation, don't initialize it and run the app, can you load a page? Just to double check that it's not caused by another library/django app that's not 3.12 ready yet.

Yes. My local does not run sentry (hence I did not catch it until my code reached staging lol)
 
> Otherwise the best way forward would be to find a minimal reproducible example -- does removing some `INSTALLED_APPS` or `MIDDLEWARE` from settings.py make the issue go away? Are there some views that work?

Thanks for the point at the right direction! After some filtering & reading debug messages, it seems that the `django_debug_toolbar` package is the culprit -- well stuff works after I disabled it. But I'll leave it as of now to see if other error pops out 😁
As a workaround, I've disabled the toolbar whenever sentry is activated hehe

**Comment by antonpirker** [comment] 2023-12-18 14:55
Hey @kwongtn! Thanks for the update. 
Good to hear you found a work around. 
Probably Django Debug Toolbar and Sentry both monkey patch the same function and something is messing things up when this happens.

**Comment by szokeasaurusrex** [comment] 2024-01-05 13:37
Hi @kwongtn, while I was attempting to reproduce this issue, I encountered a line in the Django Debug Toolbar's documentation which states that the Django Debug Toolbar [does not support ASGI apps](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#django-channels-async). Based on the information in this issue, it appears that you have only observed this error in an ASGI application with the Django Debug Toolbar enabled. Since enabling the Django Debug Toolbar in an ASGI application is an unsupported use case, we have decided to close this issue for now because it is quite likely that the Django Debug Toolbar's lack of support for ASGI apps is the root cause of the error.

If you ever encounter this error again while the Django Debug Toolbar is disabled, or if you encounter the error in a WSGI app, please let us know by reopening the issue! 😀

**Closed** 2024-01-05 13:37 UTC
Labels: Type: Bug, Integration: Django, Python:3.12
