### ISSUE TITLE
TypeError: getresponse() got an unexpected keyword argument 'buffering'

### ISSUE THREAD

**Issue by cancan101** [getsentry/sentry-python#68] opened 2018-09-21 14:32 UTC
```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/stdlib.py", line 38, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

```

**Comment by untitaker** [comment] 2018-09-21 15:29
BTW, this error is actually expected in Python 3, see here: https://github.com/urllib3/urllib3/blob/e38125dbdb9db46ad3c3f3a9b507994fbfe34499/src/urllib3/connectionpool.py#L376-L378

it's just that it should be caught before you see it. I suspect that this is not the cause of your issues, and that there's a significant part of the stacktrace missing from your bugreport.

**Comment by mitsuhiko** [comment] 2018-09-24 07:45
I am going to close this as this seems to not be us.

**Closed by mitsuhiko** 2018-09-24 07:45 UTC
Labels: help wanted, question

**Comment by banxi1988** [comment] 2019-08-21 06:55
I know it seems not related to this issue.
while since we migrate from raven to sentry-python we begin to got this error:
![image](https://user-images.githubusercontent.com/726774/63409260-693cc300-c423-11e9-8742-812692508b0a.png)

our server env:
runtime: .6.5 (3.6.5 (default, Aug  6 2018, 05:43:44)  [GCC 5.4.0 20160609])
sentry.python: 0.10.2
