### ISSUE TITLE
Sentry events are created for SOME warnings that are ignored

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry-python#2188] opened 2023-06-22 13:12 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.22.1

### Steps to Reproduce

I have sentry set up to create events for warnings. I also have the following in my configuration:

```python
logging.captureWarnings(capture=True)
warnings.filterwarnings("ignore", "(Possibly )?corrupt EXIF data", UserWarning)
warnings.filterwarnings("ignore", "Metadata Warning.*had too many entries", UserWarning)
warnings.filterwarnings("ignore", "Metadata Warning.*had no entries", UserWarning)
warnings.filterwarnings("ignore", ".*exceeds limit .*", Image.DecompressionBombWarning)
# Triggered by Pillow:
warnings.filterwarnings("ignore", ".*timestamp seems very low; regarding as unix.*")
# See https://github.com/celery/kombu/issues/1357
warnings.filterwarnings("ignore", "No hostname was supplied")
```

My goal is to ignore a bunch of warnings that trigger too often but are a non-issue, while creating events for any other warnings.

Python itself does not log any of the above warnings (it does if I remove the relevant line). Python itself also does log other warnings (my setup basically logs anything info+ to stdout).

For the above example, warnings that match `timestamp seems very low; regarding` and `exceeds limit` end up in Sentry as new events, but all the others do not. What confuses me the most is that _some_ of these ignored warnings end up in entry, while others do not.

### Expected Result

No ignored warnings should show up in Sentry as events.

### Actual Result

**Some** warnings show up, but others do not.

**Comment by WhyNotHugo** [comment] 2023-06-22 13:13
This is a Django project, all the relevant bits of my settings are:

```py
LOGLEVEL = env.str("LOGLEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "production": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[%(levelname)8s %(asctime)s] %(name)s:%(lineno)d  %(message)s",
            "datefmt": "%F %H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "production",
        },
        "sentry": {
            "level": "WARNING",
            "class": "sentry_sdk.integrations.logging.EventHandler",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "sentry"],
            "level": LOGLEVEL,
        },
        "botocore": {
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": LOGLEVEL,
            "propagate": False,
        },
        "parso": {
            "level": "INFO",
            "propagate": False,
        },
        "zeep": {
            "level": "INFO",
            "propagate": False,
        },
        "idf": {
            "level": LOGLEVEL,
            "propagate": True,
        },
        "django.security.DisallowedHost": {
            "handlers": [],
            "propagate": False,
        },
        "payments": {
            "level": "DEBUG",
            "propagate": False,
        },
        "kombu.connection": {
            # See https://github.com/celery/kombu/issues/1357
            "level": "ERROR",
            "propagate": False,
        },
        "fontTools": {
            "level": "WARNING",
        },
        "daphne.http_protocol": {  # Daphne is too verbose for development.
            "level": "INFO",
        },
    },
}
logging.captureWarnings(capture=True)
warnings.filterwarnings("ignore", "(Possibly )?corrupt EXIF data", UserWarning)
warnings.filterwarnings("ignore", "Metadata Warning.*had too many entries", UserWarning)
warnings.filterwarnings("ignore", "Metadata Warning.*had no entries", UserWarning)
warnings.filterwarnings("ignore", ".*exceeds limit .*", Image.DecompressionBombWarning)
# Triggered by Pillow:
warnings.filterwarnings("ignore", ".*timestamp seems very low; regarding as unix.*")
# See https://github.com/celery/kombu/issues/1357
warnings.filterwarnings("ignore", "No hostname was supplied")


# ...

def before_send(event, hint):
    from django.db.utils import InterfaceError

    if "exc_info" in hint:
        exc_type, exc_value, tb = hint["exc_info"]
        if isinstance(exc_value, InterfaceError):
            event["fingerprint"] = ["db-interface-error"]
    return event


init_sentry(
    attach_stacktrace=True,
    before_send=before_send,
    integrations=[
        AwsLambdaIntegration(timeout_warning=True),
        CeleryIntegration(),
        DjangoIntegration(),
        LoggingIntegration(event_level=logging.WARNING),
    ],
    release=version,
    in_app_exclude=["logging"],
    ignore_errors=["idf.core.views.TestException"],
    traces_sample_rate=0,
    environment=TENANT_SLUG,
)

ignore_logger("django.security.DisallowedHost")
# CeleryIntegration gets us far better logging than this one (it includes
# arguments and variables, and finer grained detail). Since celery events get
# duplicated, ignore this other one:
ignore_logger("celery.app.trace")
```

**Comment by WhyNotHugo** [comment] 2023-07-02 16:40
My sentry quota has dried up again this month, due to thousands of these ignored events.

**Comment by szokeasaurusrex** [comment] 2023-10-27 11:48
@WhyNotHugo I am trying to reproduce your issue, and I wanted to clarify one point: You stated that only some of your ignored warnings show up in Sentry, not all of them, and that specifically with the configuration you provided, only the warnings matching `timestamp seems very low; regarding` and `exceeds limit` showed up in Sentry, and other warnings did not.

Did the warnings matching `timestamp seems very low; regarding` and `exceeds limit` show up in Sentry every time they occurred, or only some of the time?

**Comment by WhyNotHugo** [comment] 2023-10-27 12:37
> Did the warnings matching timestamp seems very low; regarding and exceeds limit show up in Sentry every time they occurred, or only some of the time?

I believe that they show up every single time.

**Comment by szokeasaurusrex** [comment] 2023-10-27 14:59
@WhyNotHugo can you confirm that you are still observing this problem on the latest SDK version? I am currently trying to reproduce your bug by calling `warnings.filterwarnings("ignore", ".*timestamp seems very low; regarding as unix.*")` and then raising a warning containing that exact string with `warnings.warn("timestamp seems very low; regarding as unix")`, and the warning is not showing up in Sentry, as expected. But, other warnings that do not match the pattern are showing up, also as expected. 

If you are still observing the problem, can you please specify from where exactly in your code the warnings are being raised, and provide any other information that might help me to reproduce this bug?

**Comment by WhyNotHugo** [comment] 2023-10-27 15:10
The warning is emitted by a transitive dependency, the stack trace is pretty deep:

```
  File "threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "debug_toolbar/middleware.py", line 49, in __call__
    return self.get_response(request)
  File "asgiref/current_thread_executor.py", line 81, in run_until_future
    work_item.run()
  File "django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "django_renderpdf/views.py", line 158, in get
    return self.render(
  File "django_renderpdf/views.py", line 147, in render
    helpers.render_pdf(
  File "django_renderpdf/helpers.py", line 128, in render_pdf
    ).write_pdf(
  File "__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "weasyprint/document.py", line 399, in write_pdf
    pdf = generate_pdf(self, target, zoom, **options)
  File "weasyprint/pdf/__init__.py", line 261, in generate_pdf
    pdf_fonts = build_fonts_dictionary(
  File "weasyprint/pdf/fonts.py", line 27, in build_fonts_dictionary
    font.clean(cmap, hinting)
  File "weasyprint/pdf/stream.py", line 116, in clean
    subsetter.subset(self.ttfont)
  File "fontTools/subset/__init__.py", line 3476, in subset
    self._prune_pre_subset(font)
  File "fontTools/subset/__init__.py", line 3232, in _prune_pre_subset
    table = font[tag]
  File "fontTools/ttLib/ttFont.py", line 452, in __getitem__
    table = self._readTable(tag)
  File "fontTools/ttLib/ttFont.py", line 469, in _readTable
    table.decompile(data, self)
  File "fontTools/ttLib/tables/_g_l_y_f.py", line 99, in decompile
    loca = ttFont["loca"]
  File "fontTools/ttLib/ttFont.py", line 452, in __getitem__
    table = self._readTable(tag)
  File "fontTools/ttLib/ttFont.py", line 469, in _readTable
    table.decompile(data, self)
  File "fontTools/ttLib/tables/_l_o_c_a.py", line 15, in decompile
    longFormat = ttFont["head"].indexToLocFormat
  File "fontTools/ttLib/ttFont.py", line 452, in __getitem__
    table = self._readTable(tag)
  File "fontTools/ttLib/ttFont.py", line 469, in _readTable
    table.decompile(data, self)
  File "fontTools/ttLib/tables/_h_e_a_d.py", line 62, in decompile
    log.warning(
  File "__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "__init__.py", line 1634, in _log
    self.handle(record)
  File "__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "__init__.py", line 978, in handle
    self.emit(record)
```

The exact line that triggers this warning seems to be: https://github.com/fonttools/fonttools/blob/4.41.1/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L62

**Comment by szokeasaurusrex** [comment] 2023-10-30 08:54
Thanks for the information, I will continue investigating

**Comment by szokeasaurusrex** [comment] 2023-10-30 10:46
@WhyNotHugo if the warning you are observing is, in fact, being triggered by the [line you linked](https://github.com/fonttools/fonttools/blob/4.41.1/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L62), then I believe that the behavior you observed is expected.

## Explanation
The line that you linked is triggering the warning by calling `log.warning` (where `log` is a `logging.Logger` instance), rather than by calling `warnings.warn`. However, the `warnings.filterwarnings` calls you provided when initially opening the issue only affect warnings created from calls to the `warnings` module; any warnings originating from the `logging` module should be unaffected.

You can observe that `warnings.filterwarnings` only affects warnings triggered by the `warnings` module by running the following code snippet:

```python
import logging
import warnings

log = logging.getLogger(__name__)
warnings.filterwarnings("ignore", "Ignored warning.*")

# This line will not be shown due to the filterwarnings call
warnings.warn("Ignored warning (from warnings)")

# This line will be shown
warnings.warn("Not an ignored warning")

# Despite filterwarnings call, we expect to see this line because it comes from logging, not warnings
log.warning("Ignored warning (from log)")
```

When running the above code, you should expect to see the following output, which demonstrates that `warnings.filterwarnings` only affects the warnings triggered by `warnings.warn`, not by `log.warning`:
```
/path/to/script.py:11: UserWarning: Not an ignored warning
  warnings.warn("Not an ignored warning")
Ignored warning (from log)
```

The fact that these warnings are being emitted by separate loggers could also explain why they are missing from the Python warning logs, even though they appear in Sentry.

## Solution

To prevent these logger warnings from showing up in Sentry, you will need to filter them some other way, since `warnings.filterwarnings` cannot filter these logger warnings.

One possible solution would be to filter the warnings in [`before_send`](https://docs.sentry.io/platforms/python/configuration/filtering/#using-platformidentifier-namebefore-send-), which I see you are already using for another purpose. To filter the warnings you wish to ignore, you would need to modify the `before_send` function to inspect the warning messages and determine whether the warning event should be discarded or sent to Sentry. You should be able to access the warning message via `hint["log_record"].message` from within the `before_send` function; note that not all hints have a `log_record` key, so make sure to handle this case. Once you determine whether you would like to keep or discard the event, you can return `None` to discard or return the `event` to send it to Sentry. 

##
I am closing this issue for now, since it seems the behavior you noted is expected, and you should be able to filter the warnings you wish to ignore with `before_send`. If you need any further assistance, please feel free to contact us. Additionally, if you find any instances where `warnings.filterwarnings` is failing to prevent a warning triggered by `warnings.warn` from reaching Sentry, please reopen this issue, since that would indicate that we do, in fact, have a bug here.

**Closed by szokeasaurusrex** 2023-10-30 10:46 UTC
Labels: Type: Bug, Integration: Logging

**Comment by WhyNotHugo** [comment] 2023-10-30 12:13
Thanks for figuring this out, it's pretty obvious in hindsight, but it never would have occurred to me.
