### ISSUE TITLE
Transaction doesn't work with FastAPI

### ISSUE THREAD

**Issue by ShuaiShao93** [getsentry/sentry-python#2569] opened 2023-12-07 01:10 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.38.0

### Steps to Reproduce

1. Create main.py
```
import sentry_sdk
from fastapi import FastAPI
import time

sentry_sdk.init(
    dsn=$DSN,
    profiles_sample_rate=1.0,
    traces_sample_rate=1.0,
    environment="dev",
    release="1.0",
    debug=True,    
)

api = FastAPI()


@api.get("/sentry-debug")
async def trigger_error():
    with sentry_sdk.start_transaction(op="task", name="test2"):
        for _ in range(100):
            time.sleep(0.01)

async def test1():
    with sentry_sdk.start_transaction(op="task", name="test1"):
        for _ in range(100):
            time.sleep(0.01)

import asyncio
asyncio.run(test1())
```

2. run `gunicorn main:api -k uvicorn.workers.UvicornWorker`
3. Check sentry.io and confirm test1 showed up
4. Open `http://localhost:8000/sentry-debug` on browser
5. Can see this log on terminal
```
 [sentry] DEBUG: [Tracing] Starting <task> transaction <test2>
 [sentry] DEBUG: [Profiling] Initializing profile
 [sentry] DEBUG: [Profiling] Starting profile
 [sentry] DEBUG: [Profiling] Stopping profile
 [sentry] DEBUG: [ASGI] Set transaction name and source in event_processor: '/sentry-debug' / 'route'
 [sentry] DEBUG: [Profiling] Stopping profile
 [sentry] DEBUG: Sending envelope [envelope with 2 items (profile, transaction)]
```
7. Check sentry.io but don't see test2

### Expected Result

Both test1 and test2 on sentry.io

### Actual Result

test1 works, but test2 doesn't show up

**Comment by antonpirker** [comment] 2023-12-07 08:35
Hey @ShuaiShao93 thanks for writing in!

* So `test1` is a normal function that is called when your `main.py` is executed. The transaction is created manually and everything works as excepted. 

* `trigger_error` is an FastAPI route. The Sentry SDK automatically detects that you are using FastAPI and will automatically create a transaction for each request to your routes. So in this case a transaction called `/sentry-debug` has been created and sent to Sentry.  When you call `start_transaction(op="task", name="test2")` this would create a new transaction `tests2` in the automatically created transaction `/sentry-debug`. This is not supported, this is why your manual create transaction does not show up in Sentry in this case. 

Hope this helps!

**Comment by ShuaiShao93** [comment] 2023-12-08 20:28
This is blocking us, can someone take a look?

**Comment by antonpirker** [comment] 2023-12-11 09:43
Thanks for the great reply and posting of the sentry DEBUG log output.
So when reading the DEBUG log sentry is starting a transaction, then. sets the name to `/sentry-debug` and then also sends the transaction in an envelope to Sentry. So everything looks good!

I just checked your internal stats and on Dec 7th when you wrote your last reply a small percentage of all the data you sent to Sentry was dropped in the SDK because of "network errors". So the SDK was not able to upload to the server. 

Can you check if there was some network/internet problem on your end at that time? If now I would just retry it again and see if it works this time. Also one thing: performance data takes some moments to be ingested, so please wait for half a minute or so after running your script to check if the data is already there.

I also noticed that you have other environments (not "dev") that have a lot of FastAPI transactions. So maybe you could check what the difference is between your sample project and the project that is sending FastAPI transactions in your organization.

**Comment by antonpirker** [comment] 2023-12-12 08:36
What FastAPI version do you use?

**Comment by antonpirker** [comment] 2023-12-12 08:37
And just to confirm. You use Sentry SDK 1.38.0, right?

**Comment by sentrivana** [comment] 2023-12-12 09:01
We had a similar issue recently: https://github.com/getsentry/sentry/issues/60779 Transactions leaving the SDK, but not appearing in Sentry, also with FastAPI. May be related.

**Comment by sentrivana** [comment] 2023-12-12 09:45
@ShuaiShao93 Since we might need to look at your organization in order to fix this, could you please contact our support via email at [support@sentry.io](mailto:support@sentry.io)?

**Comment by ShuaiShao93** [comment] 2023-12-12 17:25
Thanks folks! We use fastapi 0.104.1 and sentry-sdk 1.38.0.

Just sent the email to support@sentry.io

**Comment by antonpirker** [comment] 2023-12-13 11:51
I tried to reproduce this with fastapi 0.104.1 and sentry-sdk 1.38.0.

This is the slightly updated version of your reproduction code:
```
import os
import time
from fastapi import FastAPI
import sentry_sdk

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    profiles_sample_rate=1.0,
    traces_sample_rate=1.0,
    environment="dev",
    release="1.0",
    debug=True,
)

api = FastAPI()

@api.get("/sentry-debug")
async def trigger_error():
    for _ in range(100):
        time.sleep(0.01)

async def test1():
    with sentry_sdk.start_transaction(op="task", name="test1"):
        for _ in range(100):
            time.sleep(0.01)

if __name__ == "__main__":
    import asyncio
    asyncio.run(test1())
```

I ran it once using:
```
python main.py
```

And then I ran it with:
```
uvicorn main:api --reload
```
using uvicorn 0.20.0 and pointing my browser to http://localhost:8000/debug-sentry 

Both transactions ended up in Sentry:

![Screenshot 2023-12-13 at 12 51 11](https://github.com/getsentry/sentry-python/assets/202325/8851cef2-45b3-49db-b9cb-cc8136d7ca8e)

(please ignore the second transaction, I just typed the wrong URL in the browser first)

How are you running your script to trigger the FastAPI transaction?

**Comment by ShuaiShao93** [comment] 2023-12-13 16:12
I did exactly the same thing as you do, but still no luck.
```
% uvicorn main:api --reload                   
INFO:     Will watch for changes in these directories: ['/Users/ss/Documents']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [59541] using StatReload
 [sentry] DEBUG: Setting up integrations (with default = True)
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.aiohttp.AioHttpIntegration: AIOHTTP not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.boto3.Boto3Integration: botocore is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.bottle.BottleIntegration: Bottle not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.celery.CeleryIntegration: Celery not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.django.DjangoIntegration: Django not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.falcon.FalconIntegration: Falcon not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.flask.FlaskIntegration: Flask is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.httpx.HttpxIntegration: httpx is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.pyramid.PyramidIntegration: Pyramid not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.rq.RqIntegration: RQ not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sanic.SanicIntegration: Sanic not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sqlalchemy.SqlalchemyIntegration: SQLAlchemy not installed.
 [sentry] DEBUG: Setting up previously not enabled integration argv
 [sentry] DEBUG: Setting up previously not enabled integration atexit
 [sentry] DEBUG: Setting up previously not enabled integration dedupe
 [sentry] DEBUG: Setting up previously not enabled integration excepthook
 [sentry] DEBUG: Setting up previously not enabled integration logging
 [sentry] DEBUG: Setting up previously not enabled integration modules
 [sentry] DEBUG: Setting up previously not enabled integration stdlib
 [sentry] DEBUG: Setting up previously not enabled integration threading
 [sentry] DEBUG: Setting up previously not enabled integration fastapi
 [sentry] DEBUG: Setting up previously not enabled integration redis
 [sentry] DEBUG: Did not enable default integration redis: Redis client not installed
 [sentry] DEBUG: Setting up previously not enabled integration starlette
 [sentry] DEBUG: Setting up previously not enabled integration tornado
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration threading
 [sentry] DEBUG: Enabling integration fastapi
 [sentry] DEBUG: Enabling integration starlette
 [sentry] DEBUG: Enabling integration tornado
 [sentry] DEBUG: Setting SDK name to 'sentry.python.fastapi'
 [sentry] DEBUG: [Profiling] Setting up profiler in thread mode
INFO:     Started server process [59568]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
 [sentry] DEBUG: [ASGI] Created transaction (continuing trace): <Transaction(name='http://127.0.0.1:8000/sentry-debug', op='http.server', trace_id='b2aee43ee94f4877aa19e2fcb4d7cb40', span_id='84bf994ae0fadc33', parent_span_id=None, sampled=None, source='url')>
 [sentry] DEBUG: [ASGI] Set transaction name and source on transaction: 'http://127.0.0.1:8000/sentry-debug' / 'url'
 [sentry] DEBUG: [Tracing] Starting <http.server> transaction <http://127.0.0.1:8000/sentry-debug>
 [sentry] DEBUG: [Profiling] Initializing profile
 [sentry] DEBUG: [Profiling] Starting profile
 [sentry] DEBUG: [ASGI] Started transaction: <Transaction(name='http://127.0.0.1:8000/sentry-debug', op='http.server', trace_id='b2aee43ee94f4877aa19e2fcb4d7cb40', span_id='84bf994ae0fadc33', parent_span_id=None, sampled=True, source='url')>
 [sentry] DEBUG: [FastAPI] Set transaction name and source on scope: /sentry-debug / route
INFO:     127.0.0.1:54688 - "GET /sentry-debug HTTP/1.1" 200 OK
 [sentry] DEBUG: [Profiling] Stopping profile
```
<img width="1530" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/5c1e3143-faec-495c-a717-b598a0330e61">

Can this be something wrong with the settings on Sentry.io?

**Comment by ShuaiShao93** [comment] 2023-12-13 18:07
Found this option 
<img width="676" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/f10bb5d3-80c9-4f11-921a-3d85f8335cb8">

But after disabling it, still not working

**Comment by ShuaiShao93** [comment] 2023-12-13 19:53
Oh forgot to set SDN after copying your code. It seems to work now. Let me confirm with a full server

**Comment by ShuaiShao93** [comment] 2023-12-13 20:37
Ok, in our application server, there was a bug in `before_send_transaction` that causes crash, after fixing it, it works now.

Thanks folks! BTW do you think it's reasonable to crash the whole application if `before_send_transaction` crashes? Otherwise it's so hard to find it crashes.

**Comment by sentrivana** [comment] 2023-12-14 13:23
@ShuaiShao93 Thanks for the update! Good to know that you've resolved this. I'll close the issue.

If there's something wrong with `before_send_transaction`, you should get an error level log message. Which might arguably be a bit cryptic because it starts with "internal error in sentry sdk", but it should include the traceback.

**Closed by sentrivana** 2023-12-14 13:23 UTC
Labels: Integration: Starlette/FastAPI, Waiting for: Product Owner

**Comment by lambda-science** [comment] 2024-08-08 08:55
> @api.get("/sentry-debug")
> async def trigger_error():
>     for _ in range(100):
>         time.sleep(0.01)
> 
> async def test1():
>     with sentry_sdk.start_transaction(op="task", name="test1"):
>         for _ in range(100):
>             time.sleep(0.01)

I have the exact same issue as @ShuaiShao93  and I don't know how to resolve this.
Using your snippet of code I get:

```
 [sentry] DEBUG: [ASGI] Created transaction (continuing trace): <Transaction(name='http://172.18.0.5:8000//sentry-debug', op='http.server', trace_id='d96b3314d04a45059bcc1ce4da0ae460', span_id='906e7335e94839db', parent_span_id=None, sampled=None, source='url', origin='auto.http.starlette')>
 08/08/2024 08:44:32 AM [ASGI] Created transaction (continuing trace): <Transaction(name='http://172.18.0.5:8000//sentry-debug', op='http.server', trace_id='d96b3314d04a45059bcc1ce4da0ae460', span_id='906e7335e94839db', parent_span_id=None, sampled=None, source='url', origin='auto.http.starlette')>
  [sentry] DEBUG: [ASGI] Set transaction name and source on transaction: 'http://172.18.0.5:8000//sentry-debug' / 'url'
 08/08/2024 08:44:32 AM [ASGI] Set transaction name and source on transaction: 'http://172.18.0.5:8000//sentry-debug' / 'url'
  [sentry] DEBUG: [Tracing] Starting <http.server> transaction <http://172.18.0.5:8000//sentry-debug>
 08/08/2024 08:44:32 AM [Tracing] Starting <http.server> transaction <http://172.18.0.5:8000//sentry-debug>
ing profile
ing profile
  [sentry] DEBUG: [Profiling] Starting profile
 08/08/2024 08:44:32 AM [Profiling] Starting profile
  [sentry] DEBUG: [ASGI] Started transaction: <Transaction(name='http://172.18.0.5:8000//sentry-debug', op='http.server', trace_id='d96b3314d04a45059bcc1ce4da0ae460', span_id='906e7335e94839db', parent_span_id=None, sampled=True, source='url', origin='auto.http.starlette')>
 08/08/2024 08:44:32 AM [ASGI] Started transaction: <Transaction(name='http://172.18.0.5:8000//sentry-debug', op='http.server', trace_id='d96b3314d04a45059bcc1ce4da0ae460', span_id='906e7335e94839db', parent_span_id=None, sampled=True, source='url', origin='auto.http.starlette')>
  [sentry] DEBUG: [FastAPI] Set transaction name and source on scope: /sentry-debug / route
 08/08/2024 08:44:32 AM [FastAPI] Set transaction name and source on scope: /sentry-debug / route
 INFO:     172.18.0.1:43664 - "GET /sentry-debug HTTP/1.1" 200 OK
  [sentry] DEBUG: [Profiling] Stopping profile
 08/08/2024 08:44:33 AM [Profiling] Stopping profile
  [sentry] INFO: Discarded session update because of missing release
 08/08/2024 08:44:33 AM Discarded session update because of missing release
  [sentry] DEBUG: Sending envelope [envelope with 3 items (profile, transaction, internal)] project:4507706728382544 host:o4507706724843520.ingest.de.sentry.io
 08/08/2024 08:44:33 AM Sending envelope [envelope with 3 items (profile, transaction, internal)] project:4507706728382544 host:o4507706724843520.ingest.de.sentry.io
```

And not the manually triggered transaction


![Image](https://github.com/user-attachments/assets/18d508bb-74a1-413a-ae10-dc6095cfaeae)


My env
```
fastapi==0.108.0
sentry-sdk[fastapi, rq]>=2.12.0
```
