### ISSUE TITLE
Importing the sentry SDK affects the way pyserial can see serial ports on OS X

### ISSUE THREAD

**Issue by foozmeat** [getsentry/sentry-python#841] opened 2020-09-28 19:51 UTC
On MacOS 10.15.6 with python 3.7.5 from pyenv

1. `pip install pyserial==3.4 sentry-sdk==0.17.8`
2. plug in a USB serial device that provides a product name to the USB stack. An Arduino would probably work.
3. run the following script

```
from serial.tools.list_ports import comports
# import sentry_sdk

ports = comports()

for p, d, h in ports:
    print(p, d, h)
```

I get output like the following:

```
/dev/cu.usbmodem00000000001A1 Playdate USB VID:PID=1331:5740 SER=00000000001A LOCATION=20-8.2
```

4. enable the sentry_sdk import and rerun the script and now you should see something like
```
/dev/cu.usbmodem00000000001A1 n/a USB VID:PID=1331:5740 SER=00000000001A LOCATION=20-8.2
```

The device name is no longer available. What in the world?

**Comment by untitaker** [comment] 2020-09-28 21:52
>plug in a USB serial device that provides a product name to the USB stack. An Arduino would probably work.

I have issues reproducing and I believe this step could use more clarification. Is there a specific device you can reproduce this with?

**Comment by antonpirker** [comment] 2022-02-21 15:45
Because the original poster never replied and it seems like an edge case that does not do to much damage I am closing this issue.

**Closed by antonpirker** 2022-02-21 15:45 UTC
Labels: needs-information, Status: Backlog
