### ISSUE TITLE
ModuleNotFoundError: No module named 'runtime'

### ISSUE THREAD

**Issue by hoou** [getsentry/sentry-python#111] opened 2018-10-08 06:08 UTC
When trying to import `AwsLambdaIntegration` I get following Error:
```
ModuleNotFoundError: No module named 'runtime'
```

Traceback:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f0a35f42fdce> in <module>()
----> 1 from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration

~/Envs/gds/lib/python3.6/site-packages/sentry_sdk/integrations/aws_lambda.py in <module>()
     13 
     14 import __main__ as lambda_bootstrap
---> 15 import runtime as lambda_runtime
     16 
     17 

ModuleNotFoundError: No module named 'runtime'
```

Version:
```
sentry-sdk==0.3.9
```

I tried install `runtime` package, but it didn't help, because then I get:
```
~/Envs/gds/lib/python3.6/site-packages/runtime.py in <module>()
     26         from thread import get_ident
     27     except ImportError:  # pragma: no cover
---> 28         from dummy_thread import get_ident
     29 
     30 __all__ = (

ModuleNotFoundError: No module named 'dummy_thread'
```
And `pip install thread` returns:
```
No matching distribution found for thread
```

**Comment by untitaker** [comment] 2018-10-08 11:47
I believe this is the same root cause as from #110. I'm going to post some
questions there, if you could also answer them there that'd be great

**Comment by untitaker** [comment] 2018-10-23 08:34
Closing as dupe of #110

**Closed by untitaker** 2018-10-23 08:34 UTC
