### ISSUE TITLE
Questionable extraction of relevant variables by pure_eval

### ISSUE THREAD

**Issue by vmarkovtsev** [getsentry/sentry-python#939] opened 2020-12-02 10:10 UTC
I've recently hit an exception in my code: https://github.com/athenianco/athenian-api/blob/master/server/athenian/api/controllers/miners/github/release_load.py#L285

I am using `pure_eval` to extract the "interesting" vars. This time, it could do better.

![image](https://user-images.githubusercontent.com/2793551/100858777-b4e77480-348e-11eb-90fb-abce6126e15c.png)

I would expect to see `repo`, `prefix`, and `settings`, however, none of them are shown. Instead, I see completely redundant class types from `typing` and my own modules.

SDK version: 0.19.4.

**Comment by untitaker** [comment] 2020-12-02 12:05
I'm going to assign this to @alexmojaki as well since I don't know how this code works rn. I don't have the time to look into it myself at the moment.

**Comment by alexmojaki** [comment] 2020-12-02 22:13
It looks like pure_eval took the first 10 expressions starting from the top of the function definition and then sentry sorted those alphabetically. Somehow the sorting by closeness didn't work.

I tried to reproduce it with this script:

```python
import json

import sentry_sdk.serializer
from sentry_sdk.integrations.pure_eval import PureEvalIntegration

from athenian.api.controllers.miners.github.release_load import group_repos_by_release_match

# sentry_sdk.serializer.MAX_DATABAG_BREADTH = 16  # as done in athenian.api

sentry_sdk.init(
    transport=lambda event: print(
        json.dumps(event["exception"]["values"][0]["stacktrace"]["frames"][-1]["vars"], indent=2)
    ),
    integrations=[PureEvalIntegration()],
)

group_repos_by_release_match([2], {}, {})
```

Output:

```
{
  "repo": "2",
  "prefix": "'github.com/'",
  "settings": {},
  "count": "1",
  "repos": [
    "2"
  ],
  "PREFIXES[\"github\"]": "'github.com/'",
  "PREFIXES": {
    "github": "'github.com/'"
  },
  "ReleaseMatch.branch": "<ReleaseMatch.branch: 0>",
  "ReleaseMatch": "<enum 'ReleaseMatch'>",
  "ReleaseMatch.tag": "<ReleaseMatch.tag: 1>"
}
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.3/scratches/scratch_1011.py", line 17, in <module>
    group_repos_by_release_match([2], {}, {})
  File "/home/alex/work/athenian-api/server/athenian/api/controllers/miners/github/release_load.py", line 285, in group_repos_by_release_match
    rms = settings[prefix + repo]
TypeError: can only concatenate str (not "int") to str
```

If I uncomment the `MAX_DATABAG_BREADTH` line then it also includes the pointless typing stuff but it still has the most important variables at the top.

I wonder if maybe the client sends everything and then the server does its own trimming and sorting. But that wouldn't explain why the included variables for you are all the ones that appear at the top of the function.

Please see if you can create a reproducible example, because I don't know what else I can try to reproduce this.

**Comment by vmarkovtsev** [comment] 2020-12-03 07:17
I've checked the event's JSON: no, only those 10 are sent.

I am working on the reproduction now.

**Comment by vmarkovtsev** [comment] 2020-12-03 10:04
While working on the reproduction, I think that I understood the cause.

Yes, `MAX_DATABAG_BREADTH` is set to 16 for me. However, we see that only 10 variables were reported. This happened because `match_groups` had actually a huge value with sensitive data that I had to cut before making the screenshot. Thus it triggered the overall frame size limit and the remaining 6 variables got discarded, including the most important ones.

In other words, this is what happened:

- `pure_eval` determines 16 variables to show, including the most relevant ones - all good.
- Sentry sorts them in alphabetical order.
- We encounter several noisy variables, including one with a huge value. Even though `pure_eval` knows that it's less important, it goes before in alphabetical order and drains the size limit.
- Sentry discards the last 6 variables because we reached the size limit.


FWIW,
### How to reproduce

```
git clone https://github.com/athenianco/athenian-api
cd athenian-api
docker build -t reproduce-pure-eval .
echo 'AUTH0_DOMAIN=athenian.auth0.com
AUTH0_AUDIENCE=http://localhost:8080
AUTH0_CLIENT_ID=classified
AUTH0_CLIENT_SECRET=classified

SENTRY_PROJECT=<your Sentry project here>
SENTRY_KEY=<your Sentry key here>

ATHENIAN_DEFAULT_USER="auth0|5e1f6dfb57bc640ea390557b"
ATHENIAN_INVITATION_KEY=we-are-the-best
ATHENIAN_INVITATION_URL_PREFIX=http://localhost:3000/i/
ATHENIAN_JIRA_INSTALLATION_URL_TEMPLATE="https://whatever/%s"
' > reproduce-pure-eval.env
docker run -it --rm --env-file reproduce-pure-eval.env --entrypoint bash -v $(pwd):/io -p8080:8080 reproduce-pure-eval
cd /server/tests/
python3 gen_mock_db.py
# Workaround the auth
sed -i 's/self._mgmt_token = data\["access_token"\]/self._mgmt_token = "whatever"/g' /server/athenian/api/auth.py
sed -i 's/expires_in = int(data\["expires_in"\])/expires_in = 100500/g' /server/athenian/api/auth.py

# Emulate the noise
sed -i 's/count = 0/count = 0; DoS = "0" * 2000/g' /server/athenian/api/controllers/miners/github/release_load.py
# Trigger the exception
sed -i 's/rms = settings\[prefix + repo\]/rms = settings[prefix + repo + "!"]/g' /server/athenian/api/controllers/miners/github/release_load.py

python3 -m athenian.api --metadata-db 'sqlite:///mdb.sqlite' --state-db=sqlite:///sdb.sqlite --precomputed-db=sqlite:///pdb.sqlite --force-user='auth0|5e1f6dfb57bc640ea390557b' --no-google-kms
```

In another terminal:

```
curl 'http://0.0.0.0:8080/v1/metrics/prs' --data-binary '{"for":[{"repositories":["github.com/src-d/go-git"]}],"metrics":["pr-done"],"date_from":"2020-09-01","date_to":"2020-12-01","granularities":["all"],"exclude_inactive":true,"account":1,"timezone":60,"quantiles":[0,1]}'
```

**Comment by alexmojaki** [comment] 2020-12-03 11:08
> In other words, this is what happened:
> 
> * `pure_eval` determines 16 variables to show, including the most relevant ones - all good.
> * Sentry sorts them in alphabetical order.
> * We encounter several noisy variables, including one with a huge value. Even though `pure_eval` knows that it's less important, it goes before in alphabetical order and drains the size limit.
> * Sentry discards the last 6 variables because we reached the size limit.

But in your original screenshot, those aren't the first 10 variables alphabetically. `repo`, `prefix`, and `settings` should all come before `Tuple`. Instead it's the first 11 expressions in the code. Here they are in the order they appear in code:

- Iterable
- Dict
- Tuple
- List
- match_groups
- ReleaseMatch
- ReleaseMatch.tag
- ReleaseMatch.branch
- PREFIXES
- PREFIXES["github"]
- count

There's a few others like `str` which pure_eval ignores completely. sentry seems to have taken that set and ordered it alphabetically.

I don't know what's going on in your second screenshot, because those 4 variables don't seem to have any special significance. They're not the first in the code or the alphabet.

**Comment by vmarkovtsev** [comment] 2020-12-03 11:21
> `repo`, `prefix`, and `settings` should all come before `Tuple`
Yes, fair enough. There must be something else then.

Anyway, you've got the reproduction of this weirdness now :smiley: Please let me know if I can help more.

**Comment by alexmojaki** [comment] 2021-03-10 21:47
I finally got around to this. Your reproduction script worked, excellent instructions there. I see the same thing as in your last screenshot, with just 4 variables.

However, when I poked around in the code, I couldn't find anything wrong, or any trimming at all. Eventually I went to where the packet is finally sent:

https://github.com/getsentry/sentry-python/blob/b530b6f89ba9c13a9f65a0fa3f151ed42c9befe0/sentry_sdk/transport.py#L209-L219

I added a `print(json_dumps(event).decode("utf8"))`, prettified the result, and found this:

```json
              "vars": {
                "repo": "'src-d/go-git'",
                "prefix": "'github.com/'",
                "settings": {
                  "github.com/src-d/go-git": {
                    "branches": "'{{default}}'",
                    "tags": "'.*'",
                    "match": "<ReleaseMatch.tag_or_branch: 2>"
                  }
                },
                "count": "1",
                "repos": [
                  "'src-d/go-git'"
                ],
                "DoS": "'00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'",
                "PREFIXES[\"github\"]": "'github.com/'",
                "PREFIXES": {
                  "github": "'github.com/'"
                },
                "ReleaseMatch.branch": "<ReleaseMatch.branch: 0>",
                "ReleaseMatch": "<enum 'ReleaseMatch'>",
                "ReleaseMatch.tag": "<ReleaseMatch.tag: 1>",
                "match_groups": {
                  "ReleaseMatch.tag": {},
                  "ReleaseMatch.branch": {}
                },
                "List": "typing.List",
                "Dict": "typing.Dict",
                "Tuple": "typing.Tuple",
                "ReleaseMatchSetting": "<class 'athenian.api.controllers.settings.ReleaseMatchSetting'>"
              },
```

All the values are sent, in the correct order specified by pure_eval. But if I sort them alphabetically, the first 4 keys are the ones in the screenshot. So again I think the sentry server is sorting them alphabetically. I don't know if that's intentional or just a side effect of the order being lost in JSON.

This happened in both versions 0.19.4 and 1.0.0 of sentry_sdk.

You previously wrote:

> I've checked the event's JSON: no, only those 10 are sent.

Clearly that didn't apply to this reproduction since there were only 4 values. So I can only suggest trying to reproduce that case where the client sent the wrong values and double checking the final event JSON.

Either way, I can't see any signs that the pure_eval integration is doing anything wrong, but rather some other truncation somewhere in sentry. The integration can only return a dict of values and hope that they get truncated well and preserve their order.

**Comment by vmarkovtsev** [comment] 2021-03-11 06:48
Thank you @alexmojaki!
@untitaker what are your thoughts on this? Is there a way to make Sentry server not sort alphabetically? Or maybe we should solve a linear optimization problem to truncate "Dos-like" variables? I can formulate it as
```
sum(x_i) < LIMIT (all variables fit) 
x_i <= L_i (truncate each as needed)
sum((N-i) * x_i) -> max (maximize the profit with weights set according to the order of variables). 
```

**Comment by vmarkovtsev** [comment] 2021-03-11 07:31
This definition seems better:
```
sum(x_i * c_i) <= LIMIT  (all variables fit)
0 <= c_i <= 1  (ratio of each visible part of the varible)
sum((N-i) * c_i) -> max  (as many variables visible as possible, with the right order)
```

**Comment by untitaker** [comment] 2021-03-15 11:36
JSON key order cannot be preserved, we simply choose to serialize the API response in sorted order, but the order is long lost before.

The server decides to trim down to 4 values because one variable is very large, because it calculates the overal byte-size of `vars` and pops values until the byte limit is enforced. We need to find a way to improve trimming behavior on the server, but I think as a workaround one could patch MAX_DATABAG_BREADTH to be 4 or omit/trim down the too-large variable using before_send.

The corresponding server code is in https://github.com/getsentry/relay/blob/master/relay-general/src/store/trimming.rs if somebody wants to tackle this. Last time I looked into this I could not find a way to trim smart and performantly.

**Comment by alexmojaki** [comment] 2021-03-26 15:43
Here are my naive suggestions:

1. Sync the client and server trimming logic. The client shouldn't send packets that are going to be trimmed again.
2. Prioritise trimming larger variables, something like @vmarkovtsev's second suggestion. Removing a bunch of small variables to make space for one giant one is not great.
3. Change `vars` to a list instead of a dict. This would also open up room to add other metadata about each var, such as an indication that large variables (especially data structures) have been trimmed down and you're not seeing the full value.
4. Make a fresh issue or change the title. There's a lot of noise here for other readers and this doesn't seem related to pure_eval.

@vmarkovtsev try upgrading pure_eval. It should now see type hints and enums as less interesting. That won't completely solve this issue but it should help. It's also now capable of evaluating more expressions.

**Comment by antonpirker** [comment] 2022-02-28 08:45
Hello @vmarkovtsev @alexmojaki @untitaker 

Can some one tell me what the status of this is? Has something on the server side changed? Has a new issue being created like @alexmojaki suggested?

And the most important question: How do we proceed with this?
Can we close this issue in favor of a new issue or one on the server side?

**Comment by untitaker** [comment] 2022-02-28 08:47
It's rather unlikely that we will fix this on the server anytime soon, and if so I don't think it's work Sentry employees would be doing to be honest.

**Comment by antonpirker** [comment] 2022-02-28 12:47
Ok, so I will close this issue. 

If someone wants to submit a PR for this (in the `sentry` repo) please do so. We are always happy to merge PRs from the community!

**Closed by antonpirker** 2022-02-28 12:47 UTC
Labels: server-fix, Status: Backlog
