### ISSUE TITLE
Django database transaction duration has 0 duration

### ISSUE THREAD

**Issue by fredgido** [getsentry/sentry-python#1385] opened 2022-04-01 15:38 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.8

### Steps to Reproduce

1. Use sentry 1.5.8 with latest django 3.2
2. Enable django integration and transactions
3. Create a transaction of one request with database queries

### Expected Result

Queries last anything from 1ms to 20ms depending on whatever the query is
This is what happens in 1.5.7

### Actual Result

everything takes 0.01ms to 0.02ms
![image](https://user-images.githubusercontent.com/17598829/161296318-b5660ab9-a445-443e-a2ce-343523def5c9.png)

**Comment by sl0thentr0py** [comment] 2022-04-04 11:48
@fredgido I'd need some sort of minimal reproduction to take a look at this.

**Comment by fredgido** [comment] 2022-04-04 14:50
> @fredgido I'd need some sort of minimal reproduction to take a look at this.

https://gitlab.com/fred.fernandes/minimal_sentry/-/tree/master/app
Built a simple example here
![2022-04-04_14-17](https://user-images.githubusercontent.com/17598829/161570336-87a37330-6672-4d91-a91b-9339a77fe558.png)
1.5.8
![2022-04-04_14-19](https://user-images.githubusercontent.com/17598829/161570407-b5b80d4f-5f2a-43f4-a803-a5e7483f62f8.png)
1.57

do you need my traces ids?

**Comment by sl0thentr0py** [comment] 2022-04-07 11:43
uhh thanks for the report @fredgido, this is a regression caused by https://github.com/getsentry/sentry-python/pull/1368 because we got rid of the `yield` in the context manager so the time is measured incorrectly now.
will try to fix soon.

**Comment by antonpirker** [comment] 2022-04-08 13:26
Hey @fredgido !
@sl0thentr0py has created a fix for this and we will release this on Monday. 
Thanks again for reporting this. If you send me your mail address to anton [dot] pirker [at] sentry {dot} io I can send you a couple of stickers as a small "Thank you" for your contribution!

**Comment by sl0thentr0py** [comment] 2022-04-11 14:10
@fredgido should be fixed in 1.5.9, can you give it a try and reopen if persists?

**Closed by sl0thentr0py** 2022-04-11 14:10 UTC
Labels: bug, Status: Backlog, Jira
