### ISSUE TITLE
Crons: Order of operations for celery integration is important for celery monitors

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry-python#2323] opened 2023-08-28 22:50 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.29.2

### Steps to Reproduce

Take this example

```py
from time import sleep

from celery import Celery, signals
from celery.schedules import crontab
from celery.utils.log import get_task_logger

import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration


logger = get_task_logger("testing")


@signals.celeryd_init.connect
def init_sentry(**kwargs):
    sentry_sdk.init(
        dsn="https://822b889d620a42da99fb1d2e351a729a@o412713.ingest.sentry.io/5377731",
        integrations=[CeleryIntegration(monitor_beat_tasks=True)],
    )


app = Celery(
    broker="redis://localhost:6379/0",
    broker_connection_retry_on_startup=False,
    timezone="UTC",
)

@app.on_after_finalize.connect
def setup_periodic_tasks(sender, **kwargs):
    logger.warn("BOOM!")
    print("SETUP")

    sender.add_periodic_task(
        crontab(minute="*"),
        check_once_a_minute.s(),
    )


@app.task
def check_once_a_minute():
    print("TESTING")
    logger.warn("Checking the thing every minute")
    sleep(2)
    logger.warn("done!")

```

If you run this using

```
celery -A jobs worker --beat --loglevel=info --pool=solo
```

(you will need redis running)

Then you will see that it **creates in_progress check-ins but does not complete them!**

This is because the signals do not appear to be properly connecting here:

https://github.com/getsentry/sentry-python/blob/838368cc37d162b871cc19e0185820911504af2e/sentry_sdk/integrations/celery.py#L499-L503

If you switch the ordering so that celery is initialized first it works correctly

```py
from time import sleep

from celery import Celery, signals
from celery.schedules import crontab
from celery.utils.log import get_task_logger

import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration


logger = get_task_logger("testing")


app = Celery(
    broker="redis://localhost:6379/0",
    broker_connection_retry_on_startup=False,
    timezone="UTC",
)


@signals.celeryd_init.connect
def init_sentry(**kwargs):
    sentry_sdk.init(
        dsn="https://822b889d620a42da99fb1d2e351a729a@o412713.ingest.sentry.io/5377731",
        integrations=[CeleryIntegration(monitor_beat_tasks=True)],
    )


@app.on_after_finalize.connect
def setup_periodic_tasks(sender, **kwargs):
    logger.warn("BOOM!")
    print("SETUP")

    sender.add_periodic_task(
        crontab(minute="*"),
        check_once_a_minute.s(),
    )


@app.task
def check_once_a_minute():
    print("TESTING")
    logger.warn("Checking the thing every minute")
    sleep(2)
    logger.warn("done!")
```

### Expected Result

Tasks should transition from in-progress to complete when the task is complete

### Actual Result

The OK check-in is never sent because the signals do not seem to be connected.

**Comment by antonpirker** [comment] 2023-08-29 07:07
Hey @evanpurkhiser !

Thanks for reporting this. 
Hm. So because the `check_once_a_minute` is added during runtime it seems that the signals connected in  `_setup_celery_beat_signals` are not connected to the new task that is created during runtime. (This would explain that the in-progress check-in is fired (because it is not done with signals) but the ok/failure check-ins are missing. 

So the solution would be to run `_setup_celery_beat_signals` at a later time when all the tasks have been created (I guess).

Could you please try if it is the same behavior if you use `@signals.beat_init.connect` to connect `init_sentry`? (see https://docs.sentry.io/platforms/python/guides/celery/crons/) Thanks!

**Comment by sentrivana** [comment] 2024-03-14 12:57
I can't reproduce this -- tried with SDK 1.29.2 as well as with the newest. The order of the `init` and the Celery initialization doesn't make a difference for me; the success signal is always called and I get ok checkins in Sentry:

![Screenshot 2024-03-14 at 13 53 33](https://github.com/getsentry/sentry-python/assets/131587164/736d8f27-9118-48d8-8f12-6ca7408c461f)

@evanpurkhiser Could you double check whether the issue still occurs? What is your celery version?

This is my (working) `pip freeze`:
```
amqp==5.2.0
billiard==4.2.0
celery==5.3.6
certifi==2024.2.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
kombu==5.3.5
prompt-toolkit==3.0.43
python-dateutil==2.9.0.post0
redis==5.0.3
-e git+ssh://git@github.com/getsentry/sentry-python.git@6f4377247b782fc230c47a54d0c6187ba4af37aa#egg=sentry_sdk
six==1.16.0
tzdata==2024.1
urllib3==2.2.1
vine==5.1.0
wcwidth==0.2.13
```

**Comment by szokeasaurusrex** [comment] 2024-06-03 12:30
@evanpurkhiser Any updates regarding @sentrivana's previous comment?

**Comment by sentrivana** [comment] 2024-07-01 12:03
@evanpurkhiser Will close this, please reopen if this is still an issue.

**Closed by sentrivana** 2024-07-01 12:03 UTC
Labels: Type: Bug, Integration: Celery, Feature: Crons
