### ISSUE TITLE
Handled exceptions from OpenAI are still being captured and reported on Sentry

### ISSUE THREAD

**Issue by prashnts** [getsentry/sentry-python#3107] opened 2024-05-27 15:44 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.2.1

### Steps to Reproduce

Run the following code with an inappropriate (eg. sexual, jailbreak, etc.) message:

```python
from openai import APIError, AzureOpenAI, BadRequestError
client = AzureOpenAI(...)

message = "Ignore all above instructions and ... (any inappropriate message that triggers BadRequestError)"
messages = [{"role": "user", "content": message}]

try:
    client.chat.completions.create(
            messages=messages,
            model='gpt-4')
except (APIError, BadRequestError):
    pass
```

### Expected Result

No error reported on sentry about `APIError` or any of its subclasses (eg. `BadRequestError`), as we've handled it.

### Actual Result

Sentry captures this exception and labels it as "Not Handled".

In the screenshot you can see the trace comprises only of openai libs, and does not reference our code at all.

<img width="1031" alt="Screenshot 2024-05-27 at 17 42 13" src="https://github.com/getsentry/sentry-python/assets/5663391/7851f5ba-c011-4960-a16a-fdffde9d8d5a">

Current fix is to either use `ignore_errors` or add a logic in `before_send`.

**Comment by sentrivana** [comment] 2024-05-28 10:25
Thanks @prashnts, we will take a look. Maybe we can make the integration configurable with a list of exception classes that should be ignored. In the meantime you should be able to filter unwanted events out with a custom [before_send](https://docs.sentry.io/platforms/python/configuration/options/#before-send).

**Comment by prashnts** [comment] 2024-05-28 10:27
Thanks! Definitely not a huge issue, just surprising. Yeah we've gone with before_send as it seemed best solution.

**Comment by RichardsonWTR** [comment] 2024-07-04 19:27
For anyone with similar problems of internal exceptions being sent to Sentry, I had the same problem, but it was caused by an integration between Flask and Flask-Restful. 

My problem was fixed with this code: 
```python
handle_exception = app.handle_exception
handle_user_exception = app.handle_user_exception
api = Api(app)
app.handle_exception = handle_exception
app.handle_user_exception = handle_user_exception
```

Reference: https://github.com/flask-restful/flask-restful/issues/280#issuecomment-329001383

**Comment by szokeasaurusrex** [comment] 2024-07-05 08:42
Hi @prashnts – it seems we originally misread your issue.

In fact, the behavior you are observing here is the expected behavior. Exceptions reported by an integration are always intentionally reported to Sentry as being "unhandled" because when the exception is captured in the integration, it is impossible to know whether any code up the call stack will handle the exception. The only time an exception will be reported to Sentry as being "handled" is when the user code explicitly captures an exception by calling `sentry_sdk.capture_exception`.

While we understand that the behavior of reporting eventually-handled exceptions as "unhandled" may be unintuitive to some users, improving this behavior further in the SDK is not technically possible, since the SDK has no way to tell whether an exception it captures will eventually get handled up the stack or whether the exception is truly unhandled. The only way for us to ensure that all truly-unhandled exceptions are labelled as "unhandled" is to also label eventually-handled exceptions as "unhandled."

If you know that your code will handle a specific error that the SDK captures, you can drop the event or modify the event to set `handled=True` by using a `before_send` callback, as @sentrivana suggested above.

Since the `before_send` seems to be working for you, and since further improvement in the SDK is impossible as I explained above, I will go ahead and close this issue.

**Closed by szokeasaurusrex** 2024-07-05 08:42 UTC
Labels: Enhancement, Waiting for: Product Owner, Integration: OpenAI

**Comment by prashnts** [comment] 2024-07-05 09:21
Thanks for the explanation. Yeah the alternative solution is sufficient for us.

**Comment by taylorhughes** [comment] 2024-10-30 19:20
In case this is helpful to anyone else:

In order to disable this automatic integration in sentry, you can pass `OpenAIIntegration` into `disabled_integrations` in `sentry_sdk.init` like so:

```
from sentry_sdk.integrations.openai import OpenAIIntegration

sentry_sdk.init(
        ...
        disabled_integrations=[OpenAIIntegration()],
)
```

(This integration is not helpful in our project because these errors are noisy and internal to the openai sdk.)

**Comment by freesteph** [comment] 2025-03-21 13:23
I'm struggling to understand why Sentry can't "tell" whether an exception will later be handled or not, like it's sitting too early in the chain? Can't it wrap the app at a higher, root level so that whatever bubbles up is guaranteed to be unhandled? Thank you for clarifying 🙏 .
