### ISSUE TITLE
Missing integrations

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-python#46] opened 2018-09-01 00:08 UTC
* [x] httplib for breadcrumbs
* [x] requests for breadcrumbs
* [ ] aws lambda
* [ ] sanic

**Comment by kasamsharif** [comment] 2018-09-14 12:03
Can I help with some integrations?

**Comment by bendidi** [comment] 2018-09-21 12:36
what needs to be done for aws lambda integration ? 
if you could give me an idea where to start , I'm very interested in trying to implement it and making a PR.

we need something like this https://docs.sentry.io/platforms/javascript/node/?platform=node to force the waiting period of 2s before the lambda shuts down ?

**Comment by untitaker** [comment] 2018-09-21 12:45
@bendidi Does this help? https://docs.sentry.io/learn/draining/?platform=python

**Comment by cowcow02** [comment] 2018-09-21 17:42
For AWS Lambda, it is more about the transporter is default to be using threaded background worker and we need something like the `HTTPTransporter` (non-threaded) in the old raven library that could send the exception right away synchronously.

Ref: https://github.com/getsentry/raven-python/issues/1063

**Comment by untitaker** [comment] 2018-09-21 17:44
@cowcow02 we understand, but @bendidi was specifically asking about the shutdown timeout. We currently don't support aws lambda.

**Comment by cowcow02** [comment] 2018-09-21 17:47
As @bendidi was asking what needs to do for AWS lambda integration so provided a bit of information I know here :-) 

I was trying to upgrade my Zappa-powered Flask app on AWS Lambda with the new SDK and noticed the issue as well.

**Comment by mitsuhiko** [comment] 2018-09-24 07:46
@cowcow02 we will have a look at lambda but I don't quite see why the default threaded transport is not sufficient there. Are atexit handlers not called on lambda? We *do* flush out on shutdown.

**Comment by untitaker** [comment] 2018-09-24 18:38
Closing for #74 and #75

**Comment by untitaker** [comment] 2018-09-25 14:02
@bendidi @cowcow02 0.3.5 is out with AWS lamdba integration. See https://github.com/getsentry/sentry-docs/pull/380 for docs

**Comment by untitaker** [comment] 2018-09-25 19:06
https://docs.sentry.io/platforms/python/aws_lambda

**Comment by cowcow02** [comment] 2018-09-27 13:06
> @bendidi @cowcow02 0.3.5 is out with AWS lamdba integration. See [getsentry/sentry-docs#380](https://github.com/getsentry/sentry-docs/pull/380) for docs

@untitaker brilliant! let me try with the Zappa + Flask to see if things are working fine in this combination 👍

**Comment by untitaker** [comment] 2018-09-27 13:08
@cowcow02 note you likely need both Flask and AWS integrations for it to work.

Right now we only test raw AWS without Zappa or Flask, let me know if you encounter issues with combining flask and lambda

**Comment by cowcow02** [comment] 2018-09-27 13:32
If I have enough time I will try out both Flask + Lambda & Django + Lambda, as the two primary frameworks we uses on Serverless + Python

more info: for raven it was working pretty well for Django+Zappa (when HTTPTransporter is on), and for Flask+Zappa is more tricky with some missing exception I never managed to make it works. Hope this time I could manage to make it working perfectly ;-)

**Comment by cowcow02** [comment] 2018-09-27 13:40
> @cowcow02 we will have a look at lambda but I don't quite see why the default threaded transport is not sufficient there. Are atexit handlers not called on lambda? We _do_ flush out on shutdown.

To be frank I ain't quite sure why threaded transport is not working there as well, as the threading module was supported by AWS Lambda itself. As I am using Zappa on top of AWS Lambda together, it could be either one of them not giving the shutdown signal to raven properly so it never got flushed? Anyways I will simply be trying out the new integration to see how it goes :-)

**Comment by untitaker** [comment] 2018-09-27 13:42
@cowcow02 no worries, we internally figured out why AWS lambda wasn't working right. Didn't have anything with threads, it's just that AWS kills or suspends the process as soon as it considers the request done.

The integration should take care of it.

**Comment by cowcow02** [comment] 2018-10-01 21:15
I just tried the integration with the following setup:
1. Created an empty Flask application
2. Installed `sentry-sdk==0.3.7` with both  `FlaskIntegration` and `AwsLambdaIntegration` included
3. Deployed the Flask application to AWS Lambda with Zappa

And the Zappa-based Flask application will not be able to boot up with the `AwsLambdaIntegration`

Here is the minimal setup:
```
# -*- coding: utf-8 -*-
import os

import sentry_sdk
from flask import Flask, jsonify
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration
from sentry_sdk.integrations.flask import FlaskIntegration

app = Flask(__name__)
sentry_sdk.init(
    dsn=os.environ.get('sentry_dsn'),
    integrations=[
        FlaskIntegration(),
        AwsLambdaIntegration()
    ]
)

@app.route('/exception_test', methods=['GET'])
def exception_test():
    raise Exception('this is an Exception that expected to catch')

@app.route('/error_test', methods=['GET'])
def exception_test():
    error = 1 / 0
    return jsonify({
        'error': error
    })

if __name__ == "__main__":
    app.run()
```

And the following error will be returned:
`AttributeError: module '__main__' has no attribute 'make_final_handler'`

**Comment by untitaker** [comment] 2018-10-02 12:02
Also if you have the time I would apprechiate if you could give me a zipfile I can upload to Lambda to reproduce your issue. Basically, strip down your app s.t. you can still reproduce the issue, then run `zappa package` and give me the created zipfile.

**Comment by cowcow02** [comment] 2018-10-03 14:53
I ain't sure where to put this snippet so I decided to attach the whole minimal demo source code here: 
[my-demo-project.zip](https://github.com/getsentry/sentry-python/files/2442532/my-demo-project.zip)

And here is the result from `zappa package`: [my-demo-project-dev-1538559115.zip](https://github.com/getsentry/sentry-python/files/2442514/my-demo-project-dev-1538559115.zip)

**Comment by untitaker** [comment] 2018-10-03 18:08
@cowcow02 so since reproducing it with your zipfile didn't work, could you deploy with the two print-statements I posted earlier and give me their output? I am not too familiar with this entire ecosystem but I assume they'll end up in `zappa tail`?

**Comment by untitaker** [comment] 2018-10-18 17:30
I am closing this since a lot has happened since then and the issue with AWS Lambda is likely resolved

**Closed by untitaker** 2018-10-18 17:30 UTC
Labels: enhancement, help wanted
