### ISSUE TITLE
Documentation for FastAPI/Starlette ASGI not correct

### ISSUE THREAD

**Issue by lsmith77** [getsentry/sentry-python#1215] opened 2021-10-05 09:54 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
python sentry-sdk==1.4.3 via pipenv

### Steps to Reproduce

* Followed the installation instructions in an FastAPI app
* Run a HTTP request against the API

### Expected Result

Sentry logging errors

### Actual Result

```
AttributeError: 'SentryAsgiMiddleware' object has no attribute 'add_middleware'
```

### Analysis

I think the issue can be fixed by changing the way the middleware is added:

```
app = FastAPI()
app.add_middleware(SentryAsgiMiddleware)
```

That being said, I am not getting errors logged when I call a route that runs `raise HTTPException(status_code=500, detail="Test")`. So I think the middleware is still not working.

**Comment by lsmith77** [comment] 2021-10-05 10:09
so if create an exception that isn't caught by FastAPI (f.e. `raise ValueError("nope")`) it seems to log it properly. So am I wrong to assume that HTTPException should be converted or does this indeed just show that the middleware isn't properly installed?

**Comment by lsmith77** [comment] 2021-10-05 10:10
I guess this is what this blog post is addressing:
https://philstories.medium.com/integrate-sentry-to-fastapi-7250603c070f

**Comment by lsmith77** [comment] 2021-10-05 11:12
alright .. got it to work by decorating the exception handler:

```
@app.exception_handler(HTTPException)
async def custom_http_exception_handler(request, e):
    with configure_scope() as scope:
        scope.set_context("request", request)
        scope.transaction = request.scope["path"][1:]

        sentry_sdk.capture_exception(e)
    return await http_exception_handler(request, e)
```

But still wondering how to use the middlware and what I might be missing if I don't have the middleware enabled.

**Comment by AbhiPrasad** [comment] 2021-10-05 13:23
Thank you for raising an issue. You'll need to use the ASGI middleware in conjugation with `app.exception_handler`. We have to improve our documentation here - and in general have a better story around FastAPI. 

```py
app = FastAPI()

# Uncaught exceptions (like `raise Exception`) should propagate correctly
# to Sentry's error handler
# Middleware will also enable Sentry performance monitoring to work as expected
app.add_middleware(SentryAsgiMiddleware)

# To catch raised `HTTPException` exceptions as per:
# https://fastapi.tiangolo.com/tutorial/handling-errors/
# Might have to add something similar for `RequestValidationError`
@app.exception_handler(HTTPException)
async def custom_http_exception_handler(request, e):
    with sentry_sdk.configure_scope() as scope:
        scope.set_context("request", request)
        sentry_sdk.capture_exception(e)

    return await http_exception_handler(request, e)
```

For the future, we probably should just monkey patch the `exception_handler` so we take care of this outside the box.

**Comment by lsmith77** [comment] 2021-10-05 16:35
thank you. a separate section in the docs for FastAPI/Starlette would be much appreciate by who ever tries to set this up next. 

and yeah monkey patching even more.

btw my solution above also has a naiv way to set the transaction into the scope

**Comment by vladanpaunovic** [comment] 2022-02-14 09:55
Closing this as a duplicate of #829

**Closed by vladanpaunovic** 2022-02-14 09:55 UTC
Labels: good first issue, doc, Status: Backlog
