### ISSUE TITLE
Support: ignore_errors when catch the exception there and process

### ISSUE THREAD

**Issue by gotedkid195** [getsentry/sentry-python#1070] opened 2021-04-01 04:00 UTC
I have `def calculate`. How to ignore this is errors `ValidationError('Invalid value')` . I mean where these exception getting thrown? you catch the exception there and process. Thanks
```
def calculate(x, y):
   try:
       return int(x / y )
   except ValueError:
       # What are the handling steps here to eliminate this error event from occurring ?
       raise ValidationError('Invalid value')
```
i have used `def before_send`, but i dont want to have to define the generalizations when all the errors happen. I want  handle when catch the exception there and process.
```
def check_error_before_send(event, hint):
    # modify event here
    return event

sentry_sdk.init(
    before_send=check_error_before_send
)
```

**Comment by untitaker** [comment] 2021-04-01 07:08
Duplicate of #149, also please do not use the issue tracker as support channel.

**Closed by untitaker** 2021-04-01 07:08 UTC
