### ISSUE TITLE
Integration for Starlette

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#1471] opened 2022-06-20 11:30 UTC
### Problem Statement

FastAPI is a wrapper around Starlette, so in the process of builing an integration for FastAPI we can add the Starlette dedciated integraiton as well

### Solution Brainstorm

See above :)

**Comment by vladanpaunovic** [comment] 2022-06-20 11:31
duplicate of #1463

**Closed by vladanpaunovic** 2022-06-20 11:31 UTC
Labels: enhancement, new-integration
