### ISSUE TITLE
Flask error logging with exc_info not showing up in the UI

### ISSUE THREAD

**Issue by Leixor** [getsentry/sentry-python#343] opened 2019-04-16 09:13 UTC
I have a simple flask app open where i want to catch an exception and log a custom message together with the stack trace. 

This logging is done inside of a route inside a flask blueprint. 

Every other type of log works, capture_exception (where I can't put a custom message) and normal error logging (where I can't get the stack trace to show) both work.

In the example I tried to log with the logging module and the logger of the flask app (should be the same). Both get send to sentry (200 response showing up in the logs), but won't show up in the UI.

## Example
```   
# Setup 
sentry_sdk.init(
    dsn="<URL>",
    integrations=[FlaskIntegration()]
)

....
# Not working
try:
    raise Exception("test")
except Exception as e:
    logging.error("first test", exc_info=True)
    current_app.logger.error("second test", exc_info=True)
    current_app.logger.exception("third test")


# Working
try:
    raise Exception("test")
except Exception as e:
    capture_exception()
    current_app.logger.error("working error log")
```

**Comment by untitaker** [comment] 2019-04-22 18:37
>Both get send to sentry (200 response showing up in the logs)

This part is interesting. If you run with `debug=True`, you see an event going through to Sentry in both cases, but one does not show in the UI?

**Comment by antonpirker** [comment] 2022-02-28 09:12
As the OP never responded, I guess the issue is resolved or not relevant anymore. I will close this.

**Closed by antonpirker** 2022-02-28 09:12 UTC
Labels: needs-information, Status: Backlog, Integration: Flask
