### ISSUE TITLE
FastAPI: Adding middleware causes an issue to capture extra exceptions 

### ISSUE THREAD

**Issue by awalker4** [getsentry/sentry-python#2410] opened 2023-10-03 17:26 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.31.0

### Steps to Reproduce

See the example gist [here](https://gist.github.com/awalker4/fdb766354bb3ad0f699ad53ff0389c34). I can raise an error and see it captured on the platform. When I add in that middleware, the issue now captures `EndOfStream` and `WouldBlock` errors from anyio, which are also shown in the breadcrumbs.

How can I remove these?

### Expected Result

I'd expect the unhandled error to appear without the extra exceptions.

### Actual Result

Ran my example app with `uvicorn app:app --host 0.0.0.0` and hit the endpoint (`curl localhost:8000/test`). The trace from this error, with middleware, is in the gist. In the UI I see these attached to the new issue:

![Screenshot 2023-10-03 at 1 11 29 PM](https://github.com/getsentry/sentry-python/assets/3846783/322b0e60-0bc9-4fd4-a2d0-364dfd10e7c5)

**Comment by sentrivana** [comment] 2023-10-04 13:40
Hey @awalker4, thanks for raising this and for providing an easy way to repro! We'll investigate.

**Comment by fnep** [comment] 2023-10-26 06:51
We are facing the same issue. 

I'm not entirely sure if this is the reason, but for me this also seems to lead to duplicate issues. I see the same exception reported once with the errors from `anyio` and once without, what is very confusing (requires many manual issue merges).

As a workaround, we are using something hacky like this 

```
def sentry_before_send(event, hint):
    try:
        # ignore errors from anyio
        if event["exception"]["values"][0]["module"] == "anyio":
            return None
    except Exception:
        pass
    return event
```

Normally, if really somehow the exception is caught twice, the later would be filtered by the `DedupeIntegration`, I think. Now in this case the exception is the same, but the traceback object is different and so this does not work.

**Comment by antonpirker** [comment] 2023-10-31 10:42
Thanks for adding more information @fnep !

**Comment by antonpirker** [comment] 2023-11-20 14:36
Hey @awalker4 !

I have reproduced this now. And this is because FastAPI (or rather the underlying Starlette framework) is chaining exceptions and this is how Sentry is dealing with chained exceptions.

I am afraid there is nothing that I can do to get rid of the chained exceptions. But have a look at the work around that @fnep provided! This should solve your problem. 

I will close this issue.

**Closed by antonpirker** 2023-11-20 14:36 UTC
Labels: Type: Bug, Integration: Starlette/FastAPI

**Comment by awalker4** [comment] 2023-11-24 18:21
Thanks for the update!
