### ISSUE TITLE
Invalid project in DSN

### ISSUE THREAD

**Issue by alejoar** [getsentry/sentry-python#87] opened 2018-09-27 11:15 UTC
I have a sentry server set up on premises. I did this a couple weeks ago, just before you guys updated the docs with the new unified SDK.

Now I'm updating our project (Django) to use the python sdk. The problem is that in our project in sentry, the DSN I see has this format: 
```
http://something_hashed@our.ip.add.dress:9000//2
```

Now the problem comes when initializing the integration. This DSN format (note: the double slash there) makes the initialization fail in `sentry_sdk/utils.py` line 77, when `int('/2')` is attempted.

This is easily fixed by simply removing the extra slash, but might be a headache for anyone who doesn't notice that.

Not sure if the SDK should handle this or if this is an issue with Sentry itself, but at least this didn't use to happen with Raven.

**Comment by untitaker** [comment] 2018-09-27 11:17
Thanks for reporting this, we should fix this issue in both the sdk and sentry. I am not sure if I will be able to reproduce this extra slash with my local sentry instance, will check later.

**Comment by untitaker** [comment] 2018-09-27 13:53
@alejoar I can't quite reproduce the issue with the double slashes, so I am assuming it's somehow local to your sentry instance. Could you share the non-sensitive parts of your sentry.conf.py?

**Comment by mitsuhiko** [comment] 2018-09-27 14:02
This probably happens because the sentry server is misconfigured and has a trailing slash on the `system.url-prefix`. Double slashes were never permitted there, it might just be that the old SDK was more lenient in parsing it.

Going to close this as working as intended. If it turns out there are more situations in which sentry emits this on self hosted we might have to re-evaluate it.

**Closed by mitsuhiko** 2018-09-27 14:02 UTC

**Comment by alejoar** [comment] 2018-09-28 07:47
@mitsuhiko actually that parameter is not set in my `config.yml` file, maybe there is an issue with whatever the default value is?

**Comment by untitaker** [comment] 2018-09-28 07:55
@alejoar just checked and this setting is also called `SENTRY_URL_PREFIX` in `sentry.conf.py`. Perhaps that one is wrong?

**Comment by alejoar** [comment] 2018-09-28 08:19
@untitaker that's not set either. Maybe some environment variable? Some extra data: I installed via Docker, and I didn't consciously set any url-prefix-ish parameter that I can recall of.

**Comment by alejoar** [comment] 2018-09-28 13:17
@untitaker nailed it! That was it. FWIW I don't think I ever set this up.
