### ISSUE TITLE
AttributeError when setting up OTEL integration

### ISSUE THREAD

**Issue by mxplusb** [getsentry/sentry-python#1976] opened 2023-03-26 00:05 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.17.2

### Steps to Reproduce

Following the documentation, I pasted this into my `main.py` file.

```python
from opentelemetry import trace
from opentelemetry.propagate import set_global_textmap
from sentry_sdk.integrations.opentelemetry import SentrySpanProcessor, SentryPropagator

provider = trace.get_tracer_provider()
try:
    provider.add_span_processor(SentrySpanProcessor())
except Exception as e:
    capture_exception(e)
set_global_textmap(SentryPropagator())
```

PyCharm throws this error:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/7537841/227748117-16a2dc06-df57-4f70-a4e9-b06e907a0d60.png">

### Expected Result

The implementation should work as the documentation expects

### Actual Result

Here is the event information from Sentry 😉 

```json
{"event_id":"69fd2ed53af24fa2a0dfd265756b2017","project":4504901795774464,"release":"86f49d8aecc633a2be5785729ff5a9f55d6955c2","dist":null,"platform":"python","message":"","datetime":"2023-03-25T23:59:59+00:00","tags":[["environment","production"],["handled","yes"],["level","error"],["mechanism","generic"],["runtime","CPython 3.8.16"],["runtime.name","CPython"],["release","86f49d8aecc633a2be5785729ff5a9f55d6955c2"],["server_name","Siennas-MacBook-Pro.local"]],"_meta":{"exception":{"values":{"0":{"stacktrace":{"frames":{"0":{"vars":{"":{"len":28},"__builtins__":{"":{"len":153}}}}}}}}}},"_metrics":{"bytes.ingested.event":4320,"bytes.stored.event":5511},"contexts":{"runtime":{"name":"CPython","version":"3.8.16","build":"3.8.16 (default, Dec  7 2022, 01:27:54) \n[Clang 14.0.0 (clang-1400.0.29.202)]","type":"runtime"}},"culprit":"__mp_main__ in <module>","environment":"production","exception":{"values":[{"type":"AttributeError","value":"'ProxyTracerProvider' object has no attribute 'add_span_processor'","stacktrace":{"frames":[{"function":"<module>","module":"__mp_main__","filename":"main.py","abs_path":"/Users/sienna/Development/random/ner/src/arcanity/main.py","lineno":35,"pre_context":["from opentelemetry.propagate import set_global_textmap","from sentry_sdk.integrations.opentelemetry import SentrySpanProcessor, SentryPropagator","","provider = trace.get_tracer_provider()","try:"],"context_line":"    provider.add_span_processor(SentrySpanProcessor())","post_context":["except Exception as e:","    capture_exception(e)","set_global_textmap(SentryPropagator())","","# hide the warning logs"],"in_app":true,"vars":{"__builtins__":{"__build_class__":"<built-in function __build_class__>","__doc__":"\"Built-in functions, exceptions, and other objects.\\n\\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.\"","__import__":"<built-in function __import__>","__loader__":"<class '_frozen_importlib.BuiltinImporter'>","__name__":"'builtins'","__package__":"''","__spec__":"ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>)","abs":"<built-in function abs>","all":"<built-in function all>","any":"<built-in function any>"},"__cached__":"None","__doc__":"None","__file__":"'/Users/sienna/Development/random/ner/src/arcanity/main.py'","__loader__":"None","__name__":"'__mp_main__'","__package__":"''","__spec__":"None","sentry_sdk":"<module 'sentry_sdk' from '/Users/sienna/Development/random/ner/src/arcanity/venv/lib/python3.8/site-packages/sentry_sdk/__init__.py'>","simplefilter":"<function simplefilter at 0x103597e50>"}}]},"mechanism":{"type":"generic","handled":true}}]},"extra":{"sys.argv":["/Users/sienna/Development/random/ner/src/arcanity/main.py"]},"fingerprint":["{{ default }}"],"grouping_config":{"enhancements":"eJybzDRxY3J-bm5-npWRgaGlroGxrpHxBABcYgcZ","id":"newstyle:2019-10-29"},"hashes":["a9db8b431d9ba84f40ebfae0039ec397"],"ingest_path":[{"version":"23.3.1","public_key":"XE7QiyuNlja9PZ7I9qJlwQotzecWrUIN91BAO7Q5R38"}],"key_id":"3053338","level":"error","location":"main.py","logger":"","metadata":{"display_title_with_tree_label":false,"filename":"main.py","function":"<module>","type":"AttributeError","value":"'ProxyTracerProvider' object has no attribute 'add_span_processor'"},"modules":{"aioauth":"1.5.1","aiocontextvars":"0.2.2","aiofiles":"23.1.0","aiohttp":"3.8.4","aiosignal":"1.3.1","async-timeout":"4.0.2","attrs":"22.2.0","blis":"0.7.9","catalogue":"2.0.8","certifi":"2022.12.7","charset-normalizer":"3.1.0","click":"8.1.3","confection":"0.0.4","cymem":"2.0.7","deprecated":"1.2.13","en-core-web-lg":"3.5.0","en-core-web-md":"3.5.0","en-core-web-sm":"3.5.0","en-core-web-trf":"3.5.0","filelock":"3.10.0","frozenlist":"1.3.3","httptools":"0.5.0","huggingface-hub":"0.13.2","idna":"3.4","importlib-metadata":"6.0.1","jinja2":"3.1.2","langcodes":"3.3.0","markupsafe":"2.1.2","mpmath":"1.3.0","multidict":"6.0.4","murmurhash":"1.0.9","networkx":"3.0","numpy":"1.24.2","opentelemetry-api":"1.17.0","opentelemetry-distro":"0.38b0","opentelemetry-instrumentation":"0.38b0","opentelemetry-sdk":"1.17.0","opentelemetry-semantic-conventions":"0.38b0","packaging":"23.0","pathy":"0.10.1","pip":"23.0.1","preshed":"3.0.8","pydantic":"1.10.6","pyyaml":"6.0","regex":"2022.10.31","requests":"2.28.2","sanic":"22.12.0","sanic-routing":"22.8.0","sentry-sdk":"1.17.0","setuptools":"56.0.0","smart-open":"6.3.0","spacy":"3.5.1","spacy-alignments":"0.9.0","spacy-legacy":"3.0.12","spacy-loggers":"1.0.4","spacy-transformers":"1.2.2","srsly":"2.4.6","sympy":"1.11.1","thinc":"8.1.9","tokenizers":"0.13.2","torch":"2.0.0","tqdm":"4.65.0","transformers":"4.26.1","typer":"0.7.0","typing-extensions":"4.5.0","ujson":"5.7.0","urllib3":"1.26.15","uvloop":"0.17.0","wasabi":"1.1.1","websockets":"10.4","wrapt":"1.15.0","yarl":"1.8.2","zipp":"3.15.0"},"nodestore_insert":1679788801.723663,"received":1679788799.99418,"sdk":{"name":"sentry.python.sanic","version":"1.17.0","integrations":["aiohttp","argv","atexit","dedupe","excepthook","logging","modules","redis","sanic","stdlib","threading"],"packages":[{"name":"pypi:sentry-sdk","version":"1.17.0"}]},"timestamp":1679788799.284841,"title":"AttributeError: 'ProxyTracerProvider' object has no attribute 'add_span_processor'","transaction_info":{},"type":"error","version":"7"}
```

**Comment by antonpirker** [comment] 2023-03-28 09:11
Hey @mxplusb !

Thanks for reporting this.
It seems that there is no TracerProvider set (so `get_tracer_provider()` returns a `ProxyTracerProvider` that does not have the method `add_span_processor()`.

Can you show me how you start your app?

**Comment by TillSilvester** [comment] 2023-12-20 09:48
The above specified code is exactly what is in the documentation and i can also reproduce this issue 
Could you  please improve the docs?

**Comment by nikiticus** [comment] 2023-12-22 02:11
Got the same issue. @antonpirker the app in our cases is started with `/path/to/python app.py`. Sentry on its own works fine, but but using the [opentelementry instructions](https://docs.sentry.io/platforms/python/performance/instrumentation/opentelemetry/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fplatforms%2Fpython%2Fperformance) fails.

**Comment by nikiticus** [comment] 2023-12-22 02:28
It seems opentelemetry requires some additional setup to use. The simplest way is documented [here](https://opentelemetry.io/docs/instrumentation/python/manual/#traces).

Basically, you need to replace 

```
provider = trace.get_tracer_provider()
```

with 

```
provider = TracerProvider()
trace.set_tracer_provider(provider)
```

**Comment by heitorpolidoro** [comment] 2023-12-22 12:49
Still not working for me.
I followed the instructions in https://docs.sentry.io/platforms/python/performance/instrumentation/opentelemetry/

```python
from opentelemetry import trace
from opentelemetry.propagate import set_global_textmap
from sentry_sdk.integrations.opentelemetry import SentrySpanProcessor, SentryPropagator

provider = trace.get_tracer_provider()
provider.add_span_processor(SentrySpanProcessor())
set_global_textmap(SentryPropagator())
```
Give the error:
```
app.py:13: in <module>
    provider.add_span_processor(SentrySpanProcessor())
E   AttributeError: 'ProxyTracerProvider' object has no attribute 'add_span_processor'
```

And the @nikiticus solution give me another error:
```
app.py:13: in <module>
    provider = TracerProvider()
E   TypeError: Can't instantiate abstract class TracerProvider with abstract method get_tracer
```

**Comment by sentrivana** [comment] 2024-01-11 11:06
Reopening since the docs still need fixing -- until the docs fix is done and merged, here's a minimal example:
```
import time

import sentry_sdk
from opentelemetry import trace
from opentelemetry.propagate import set_global_textmap
from opentelemetry.sdk.trace import TracerProvider
from sentry_sdk.integrations.opentelemetry import SentryPropagator, SentrySpanProcessor

sentry_sdk.init(
    dsn=<YOUR_DSN>,
    enable_tracing=True,
    instrumenter="otel",
)

provider = TracerProvider()
provider.add_span_processor(SentrySpanProcessor())
trace.set_tracer_provider(provider)
set_global_textmap(SentryPropagator())

tracer = trace.get_tracer(__name__)

# Start a new span
with tracer.start_as_current_span("test_otel_span"):
    print("Processing some data...")
    # Simulate some processing
    time.sleep(3)
```

Can you try this out @heitorpolidoro and see if it works for you too?

**Comment by heitorpolidoro** [comment] 2024-01-11 14:30
@sentrivana Looks like it works
![image](https://github.com/getsentry/sentry-python/assets/14806300/d6bcc282-56ac-45c4-b9b8-8ab7d0767d33)
Thanks

**Closed** 2024-01-12 08:33 UTC
Labels: Docs, Discussion, Waiting for: Product Owner

**Comment by sentrivana** [comment] 2024-01-12 08:34
The updated example will be up shortly at https://docs.sentry.io/platforms/python/performance/instrumentation/opentelemetry/.
