### ISSUE TITLE
Fix race condition in Django tests

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1800] opened 2022-12-22 09:02 UTC
We use tox for running our test suite. We should upgrade from version 3 to version 4. 
Version 4 of tox was a complete rewrite of the tool, so the upgrade does not work out of the box. 

Some trial an error has been done already:

Here is our working test suite with latest tox 3:
https://github.com/getsentry/sentry-python/actions/runs/3752739310/jobs/6375243340

And here is the failing test suite with tox 4.0.16:
https://github.com/getsentry/sentry-python/actions/runs/3752701362/jobs/6375159457

Because I could not find the root cause of the problem, I have created a issue in the tox project:
https://github.com/tox-dev/tox/issues/2769

**Comment by asottile-sentry** [comment] 2023-01-03 17:57
so it turns out this isn't actually an issue with `tox` -- but a race condition in the tests themselves.  they all share the same postgres database so if two tests run at the same time they race with each other

probably the best fix is to give each test instace a unique postgres database that way they can't stomp on each other 

here is a fairly reliable way to reproduce the problem:

first set up the virtualenvs for the environments that we'll use

```bash
rm -rf .tox
tox --notest -e py3.9-django-v3.0,py3.9-django-v4.1
.tox/py3.9-django-v3.0/bin/pip install pytest-xdist pytest-repeat
.tox/py3.9-django-v4.1/bin/pip install pytest-xdist pytest-repeat
```

then in one tab run postgres:

```bash
docker run -p 5432:5432 -e POSTGRES_PASSWORD=sentry  --rm -ti postgres
```

then in one tab run this:

```bash
export SENTRY_PYTHON_TEST_POSTGRES_PASSWORD=sentry
export SENTRY_PYTHON_TEST_POSTGRES_NAME=ci_test
export SENTRY_PYTHON_TEST_POSTGRES_USER=postgres
.tox/py3.9-django-v3.0/bin/pytest --count 100 -n 5 tests/integrations/django/test_basic.py -k test_user_captured
```

and in the other tab run this (the only difference is `3.0` -> `4.1`)

```bash
export SENTRY_PYTHON_TEST_POSTGRES_PASSWORD=sentry
export SENTRY_PYTHON_TEST_POSTGRES_NAME=ci_test
export SENTRY_PYTHON_TEST_POSTGRES_USER=postgres
.tox/py3.9-django-v4.1/bin/pytest --count 100 -n 5 tests/integrations/django/test_basic.py -k test_user_captured
```

this will show the same errors as was seen in CI when attempting tox 4.x

**Comment by sentrivana** [comment] 2024-04-08 12:14
Closing in favor of https://github.com/getsentry/sentry-python/issues/2586

**Comment by asottile-sentry** [comment] 2024-04-09 15:24
@sentrivana I think it's still important to fix the issue I outlined above (which is somewhat separate from the tooling upgrade -- but was (?) made worse by it for some reason)

**Comment by sentrivana** [comment] 2024-04-10 09:38
@asottile-sentry Thanks for the follow up -- we gave each test instance its own DB with a random name in https://github.com/getsentry/sentry-python/pull/2690/files#diff-569b5fa9a41e8ff8c55884b4478e01fee5f41d8849627c474c18215e2615f468 so this should now be fixed.

**Comment by asottile-sentry** [comment] 2024-04-10 12:43
I don't think that fixes the problem -- it just makes it much rarer and more difficult to debug.  it should use the `pid` probably to avoid collisions

**Comment by antonpirker** [comment] 2024-04-18 08:34
Yes, maybe `pid` would make it better. But it is "good enough" as it is now, so I will close this issue again.

**Closed** 2024-04-18 08:34 UTC
Labels: enhancement
