### ISSUE TITLE
Exceptions in blinker when exiting Flask app

### ISSUE THREAD

**Issue by vasa-chi** [getsentry/sentry-python#2183] opened 2023-06-20 09:26 UTC
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.25.1

### Steps to Reproduce

1. Start a simple Flask app using `flask --app run`.
2. Kill it using Ctrl-C.

My sample app:
```py
from flask import Flask
import sentry_sdk

sentry_sdk.init(dsn="")

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
```

Python version: 3.7.13

Dependencies:
```
Flask==2.2.5
sentry-sdk[flask]==1.25.1
```

pip freeze:
```
blinker==1.6.2
certifi==2023.5.7
click==8.1.3
Flask==2.2.5
importlib-metadata==6.7.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
sentry-sdk==1.25.1
typing_extensions==4.6.3
urllib3==2.0.3
Werkzeug==2.2.3
zipp==3.15.0
```

### Expected Result

Normal exit.

### Actual Result

Exceptions in `blinker` cleanup code:

```
^CException ignored in: <bound method Signal._cleanup_receiver of <blinker.base.NamedSignal object at 0x10cec5550; 'before-render-template'>>
Traceback (most recent call last):
  File "/Users/vasachi/.virtualenvs/flask-setry-test/lib/python3.7/site-packages/blinker/base.py", line 433, in _cleanup_receiver
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Signal._cleanup_receiver of <blinker.base.NamedSignal object at 0x10ce43190; 'request-started'>>
Traceback (most recent call last):
  File "/Users/vasachi/.virtualenvs/flask-setry-test/lib/python3.7/site-packages/blinker/base.py", line 433, in _cleanup_receiver
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Signal._cleanup_receiver of <blinker.base.NamedSignal object at 0x10ce43650; 'got-request-exception'>>
Traceback (most recent call last):
  File "/Users/vasachi/.virtualenvs/flask-setry-test/lib/python3.7/site-packages/blinker/base.py", line 433, in _cleanup_receiver
TypeError: 'NoneType' object is not callable
```

**Comment by vasa-chi** [comment] 2023-06-22 09:07
Oh, forgot to mention. Can only reproduce this using `blinker>=1.6`.

**Comment by visuman** [comment] 2023-07-17 09:09
Any update on this, i am also facing this issue.

**Comment by antonpirker** [comment] 2023-07-24 09:20
No news yet. We have it on our backlog, but on a low priority. So this will take some time. 
But we are always happy to accept PRs, if you want to give it a go!

**Comment by quantleap** [comment] 2023-07-24 09:27
Hi Anton, I will see if I can find the cause and submit a fix
best Tom

**Comment by ggroven** [comment] 2023-10-14 15:23
Hello, any update on this?

**Comment by antonpirker** [comment] 2023-10-16 14:34
No, sorry.

**Comment by pgjones** [comment] 2023-11-01 22:07
Blinker >= 1.7.0 will hopefully fix this, it has just been released.

**Comment by sentrivana** [comment] 2023-11-03 08:16
@vasa-chi @visuman @ggroven Folks, let us know if using `blinker>=1.7.0` fixes the issue for you.

**Comment by vasa-chi** [comment] 2023-11-03 08:46
It seems that the problem is caused by a combination of `python==3.7` and `blinker==1.6`. I can't reproduce this on `python==3.9` using any blinker versions.
`blinker==1.7` dropped support for `python==3.7`, so I guess no, it doesn't solve the issue.

**Comment by sentrivana** [comment] 2023-11-03 13:57
The base `sentry-sdk` package doesn't (and shouldn't) depend on `blinker`, only the `sentry-sdk[flask]` extra. We could add an upper bound for lower py versions to the extra, but if you install plain `sentry-sdk` and `flask` separately you'd get a different `blinker` version. However in general we shouldn't enforce an upper bound here -- as a helper tool we shouldn't dictate bounds on dependencies (unless communicating the lowest supported version of a package) since that can cause dependency issues transitively.

For folks in your situation, on an older Python version, I'd recommend pinning `blinker<1.6` locally. For those who are able to upgrade, `blinker>=1.7` should be the way to go.

**Comment by antonpirker** [comment] 2023-11-20 13:34
As there was a work around given, I will close this issue.

**Closed by antonpirker** 2023-11-20 13:34 UTC
Labels: Type: Bug, Integration: Flask
