### ISSUE TITLE
AWS Lambda Python 3.9 support

### ISSUE THREAD

**Issue by razumeiko** [getsentry/sentry-python#1170] opened 2021-08-26 13:52 UTC
### Environment

AWS Lambda with Python 3.9 runtime.
Sentry sdk version sentry-sdk==1.3.1

### Steps to Reproduce

1. Change lambda runtime to Python 3.9
2. Raise exception

### Expected Result

Error should appear in the sentry dashboard.

### Actual Result

Nothing happens.

I found that in Python 3.9 runtime, AWS has changed bootstrap location, so  `return sys.modules["__main__"].bootstrap` this is not working anymore.
I fixed it with this `sys.modules["__main__"].awslambdaricmain.bootstrap`

**Comment by aahung** [comment] 2021-09-29 00:57
@AbhiPrasad any plan to prioritize this or any hint how to contribute?

**Comment by fprochazka** [comment] 2021-10-01 21:27
I've just upgraded to 3.9 and have spent about an hour figuring out why my exceptions are not being logged anymore :-/

**Comment by AbhiPrasad** [comment] 2021-10-01 21:45
This is on our radar - we’ll take a look ASAP to try to merge in the PR and see if we need further fixes/adjustments.

**Comment by kvey** [comment] 2021-11-01 17:23
Hello! What is the status of this issue?

**Comment by AbhiPrasad** [comment] 2021-11-02 17:22
Hey @kvey, there is a PR open that seems to have slowed down. We've not gotten the bandwidth to focus on this yet, so any contributions or help is greatly appreciated!

**Comment by wjdp** [comment] 2021-11-09 17:19
Tried the fix @fprochazka suggested but sadly didn't work. Sadly have had to downgrade to 3.8 instead.

**Comment by jonapich** [comment] 2021-11-10 19:50
I was able to trick sentry in finding it by doing this:

```
from sentry_sdk.integrations.aws_lambda import get_lambda_bootstrap

detected_bootstrap = get_lambda_bootstrap()
sys.modules['bootstrap'] = detected_bootstrap.awslambdaricmain.bootstrap

sentry_sdk.init()
```

**Comment by aahung** [comment] 2021-11-11 09:17
> I was able to trick sentry in finding it by doing this:
> 
> ```
> import sys
> from sentry_sdk.integrations.aws_lambda import get_lambda_bootstrap
> 
> sys.modules['bootstrap'] = get_lambda_bootstrap().awslambdaricmain.bootstrap
> sentry_sdk.init()
> ```

@jonapich this is very helpful. Just tested and it works like a charm. The transactions are coming back.

**Comment by AbhiPrasad** [comment] 2021-11-17 13:34
This should be released as part of SDK version [`1.5.0`](https://github.com/getsentry/sentry-python/releases/tag/1.5.0), thanks to the excellent work of both @razumeiko and @tomscytale in #1239

**Closed by AbhiPrasad** 2021-11-17 13:34 UTC
Labels: bug, help wanted, serverless, Status: Backlog

**Comment by aahung** [comment] 2021-11-21 09:15
> > I was able to trick sentry in finding it by doing this:
> > ```
> > import sys
> > from sentry_sdk.integrations.aws_lambda import get_lambda_bootstrap
> > 
> > sys.modules['bootstrap'] = get_lambda_bootstrap().awslambdaricmain.bootstrap
> > sentry_sdk.init()
> > ```
> 
> @jonapich this is very helpful. Just tested and it works like a charm. The transactions are coming back.

Anyone using this workaround, please make sure it is removed before upgrading to 1.5.0, otherwise you will see this error:
```
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/dev/sync_prod_data.py", line 10, in <module>
    from shared.logger import logger
  File "/var/task/shared/logger.py", line 13, in <module>
    sentry.init()
  File "/var/task/shared/sentry.py", line 27, in init
    sys.modules["bootstrap"] = bootstrap.awslambdaricmain.bootstrap
```

**Comment by fprochazka** [comment] 2021-11-21 11:35
I've just deployed 1.5.0 and the problem is fixed, thank you!
