### ISSUE TITLE
Sanic does not actually do async error handlers!!!

### ISSUE THREAD

**Issue by autumnjolitz** [getsentry/sentry-python#634] opened 2020-02-25 23:53 UTC
These lines of code are broken whenever Sanic throws an application exception that is handled by the `@app.exception(ExceptionType)` functions.

https://github.com/getsentry/sentry-python/blob/bf48bd0681c68239ee651224b59b9d8aee78f514/sentry_sdk/integrations/sanic.py#L112-L140

This is because `server.py` is actually synchronous: 
https://github.com/huge-success/sanic/blob/16961fab9ddfd6d54f4f005c92bda1201de01ceb/sanic/server.py#L576-L579

It's an incomplete implementation and is an open issue in https://github.com/huge-success/sanic/issues/1785

This means that whenever any `app.exception(` fires, like `@app.exception(PayloadTooLarge)`, the exception handler fails to send a response to the client because the synchronous `server.py:: write_error` function cannot handle a coroutine, resulting in broken user code.

**Comment by jordangarside** [comment] 2020-03-16 06:51
We're also running into this.

**Comment by untitaker** [comment] 2020-03-16 15:24
What do I need to do to reproduce the issue with the SDK? I am working with the following test, which seems to work fine:

```diff
diff --git a/tests/integrations/sanic/test_sanic.py b/tests/integrations/sanic/test_sanic.py
index 72425ab..d27c2c5 100644
--- a/tests/integrations/sanic/test_sanic.py
+++ b/tests/integrations/sanic/test_sanic.py
@@ -92,6 +92,28 @@ def test_bad_request_not_captured(sentry_init, app, capture_events):
     assert not events
 
 
+def test_errorhandler(sentry_init, app, capture_events):
+    sentry_init(integrations=[SanicIntegration()])
+    events = capture_events()
+
+    @app.route("/error")
+    def myerror(request):
+        raise ValueError("oh no")
+
+    @app.exception(ValueError)
+    def myhandler(request, exception):
+        return response.text("too bad")
+
+    request, client_response = app.test_client.get("/error")
+    assert client_response.status == 200
+    assert client_response.body == b"too bad"
+
+    event, = events
+
+    (exception,) = event['exception']['values']
+    assert exception['type'] == 'ValueError'
+
+
 def test_error_in_errorhandler(sentry_init, app, capture_events):
     sentry_init(integrations=[SanicIntegration()])
     events = capture_events()
```

**Comment by jordangarside** [comment] 2020-03-16 16:59
Oops sorry about that, I misread this. Posted my issue in #650.

**Comment by untitaker** [comment] 2020-06-17 08:10
Closing this because there's not been any activity or response to my questions.

**Closed by untitaker** 2020-06-17 08:10 UTC
Labels: bug
