### ISSUE TITLE
TypeError raised in the celery integration when calling a task.apply_async without arguments

### ISSUE THREAD

**Issue by avallbona** [getsentry/sentry-python#2554] opened 2023-12-01 10:00 UTC
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.36.0

### Steps to Reproduce

Having a project with Python 3.9, Django 3.2.23, sentry_sdk>=1.36.0 and celery 5.2.6, with the sentry_sdk configured as:

```
sentry_sdk.init(
        release=f"project@{VERSION}",
        before_send=before_send,
        before_breadcrumb=before_breadcrumb,
        environment=ENVIRONMENT,
        integrations=[CeleryIntegration(), DjangoIntegration(), RedisIntegration()],
        ignore_errors=SENTRY_IGNORE_EXCEPTIONS,
        send_default_pii=True,
        sample_rate=min(SENTRY_EVENTS_SAMPLE_RATE, 1.0),
        traces_sample_rate=min(SENTRY_TRACES_SAMPLE_RATE, 1.0),
    )
```
when calling a task directly (not scheduled with celery beat) with the  `.apply_async()` method without params, the sentry_sdk raises a `TypeError` exception in https://github.com/getsentry/sentry-python/pull/2510/files#diff-bbcc458d29b0f1880cf429abbf8a94a5e8517f61072945d783e44fec4969a10bR169 e.g.:

```
Traceback (most recent call last):
File "/virtualenv/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/virtualenv/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner
reraise(*exc_info)
File "/virtualenv/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 115, in reraise
raise value
File "/virtualenv/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner
return f(*args, **kwargs)
File "/virtualenv/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/app/src/virus_scanner/tasks.py", line 79, in load_from_queue
load_from_queue.apply_async()
File "/virtualenv/lib/python3.9/site-packages/celery_common/tasks.py", line 57, in apply_async
return super().apply_async(args, kwargs, **options)
File "/virtualenv/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 169, in apply_async
task_started_from_beat = args[1][0] == "BEAT"
TypeError: 'NoneType' object is not subscriptable
```

### Expected Result

the task is executed properly 

### Actual Result

a 500 error is raised

**Comment by rodolfoBee** [comment] 2023-12-01 13:04
A similar issue was reported in this [internal ticket](https://sentry.zendesk.com/agent/tickets/108717).

**Comment by antonpirker** [comment] 2023-12-07 08:25
@mrcljx thanks for more information!

**Comment by slapshin** [comment] 2024-01-10 11:52
Hello! Looks like the problem is not solved.
```
File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 169, in apply_async
    task_started_from_beat = args[1][0] == "BEAT"
                             ~~~~~~~^^^
KeyError: 0
```

Maybe `KeyError` also should be added to except exceptions?

**Comment by sentrivana** [comment] 2024-01-10 12:29
Hey @slapshin, thanks for bringing this up, reopened the issue. The fix sounds good to me -- will make a PR as soon as I get to it, unless someone beats me to it.

**Comment by szokeasaurusrex** [comment] 2024-01-10 16:00
@slapshin I tried to reproduce this error so that we could add a unit test to verify that we are handling the `KeyError`. However, the only way I have figured out how to reproduce the error so far is by passing a `dict` as the first argument to `apply_async`, which violates the `apply_async` method contract, since [Celery expects](https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.apply_async) this argument to be a `tuple` or `None`. 

Did you run into this error by passing a `dict` as the first argument to `apply_async`?

**Comment by slapshin** [comment] 2024-01-11 07:11
@szokeasaurusrex ok, I'll check the code. Maybe mistake on my side. Thank you!

**Comment by slapshin** [comment] 2024-01-11 14:17
@szokeasaurusrex yes, it was my mistake. For now, everything is fine. Thank you!

**Comment by sentrivana** [comment] 2024-01-11 14:23
Thanks for reporting back @slapshin! I'll close this again.

**Closed by sentrivana** 2024-01-11 14:23 UTC
Labels: Type: Bug, Integration: Django, Waiting for: Product Owner
