### ISSUE TITLE
Sentry doesn't pick up errors via Slack Webhook

### ISSUE THREAD

**Issue by reparadocs** [getsentry/sentry-python#310] opened 2019-03-28 20:39 UTC
I'm using Django and when I cURL my endpoint, the exception is raised and logged in Sentry successfully. However, when Slack hits the endpoint through its webhook system, it somehow doesn't get logged in Sentry. I know it's still being hit because the 500 response still shows up in my logs and the error gets logged correctly in rollbar.

Here's the code:

```
@csrf_exempt
def Slack_Webhook(request):

  data = json.loads(request.body)

  raise Exception()

**Comment by untitaker** [comment] 2019-03-29 20:37
Could you initialize the SDK with `debug=True` and see if there's anything relevant?

**Comment by reparadocs** [comment] 2019-04-03 21:40
`[sentry] ERROR: Internal error in sentry_sdk 
Apr 03 14:39:22 trestle-shrine app/web.1: Traceback (most recent call last): 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 43, in capture_internal_exceptions 
Apr 03 14:39:22 trestle-shrine app/web.1:     yield 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 157, in send_event_wrapper 
Apr 03 14:39:22 trestle-shrine app/web.1:     self._send_event(event) 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 145, in _send_event 
Apr 03 14:39:22 trestle-shrine app/web.1:     raise ValueError("Unexpected status code: %s" % response.status) 
Apr 03 14:39:22 trestle-shrine app/web.1: ValueError: Unexpected status code: 403 
Apr 03 14:39:22 trestle-shrine app/web.1: ERROR:sentry_sdk.errors:Internal error in sentry_sdk 
Apr 03 14:39:22 trestle-shrine app/web.1: Traceback (most recent call last): 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 43, in capture_internal_exceptions 
Apr 03 14:39:22 trestle-shrine app/web.1:     yield 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 157, in send_event_wrapper 
Apr 03 14:39:22 trestle-shrine app/web.1:     self._send_event(event) 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 145, in _send_event 
Apr 03 14:39:22 trestle-shrine app/web.1:     raise ValueError("Unexpected status code: %s" % response.status) 
Apr 03 14:39:22 trestle-shrine app/web.1: ValueError: Unexpected status code: 403 
Apr 03 14:39:22 trestle-shrine app/web.1:  [sentry] DEBUG: Sending error event [aab269ea29cd42e1b92a2272c2c48cfc] to sentry.io project:1359428 
Apr 03 14:39:22 trestle-shrine app/web.1: DEBUG:sentry_sdk.errors:Sending error event [aab269ea29cd42e1b92a2272c2c48cfc] to sentry.io project:1359428 
Apr 03 14:39:22 trestle-shrine app/web.1:  [sentry] ERROR: Internal error in sentry_sdk 
Apr 03 14:39:22 trestle-shrine app/web.1: Traceback (most recent call last): 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 43, in capture_internal_exceptions 
Apr 03 14:39:22 trestle-shrine app/web.1:     yield 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 157, in send_event_wrapper 
Apr 03 14:39:22 trestle-shrine app/web.1:     self._send_event(event) 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 145, in _send_event 
Apr 03 14:39:22 trestle-shrine app/web.1:     raise ValueError("Unexpected status code: %s" % response.status) 
Apr 03 14:39:22 trestle-shrine app/web.1: ValueError: Unexpected status code: 403 
Apr 03 14:39:22 trestle-shrine app/web.1: ERROR:sentry_sdk.errors:Internal error in sentry_sdk 
Apr 03 14:39:22 trestle-shrine app/web.1: Traceback (most recent call last): 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 43, in capture_internal_exceptions 
Apr 03 14:39:22 trestle-shrine app/web.1:     yield 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 157, in send_event_wrapper 
Apr 03 14:39:22 trestle-shrine app/web.1:     self._send_event(event) 
Apr 03 14:39:22 trestle-shrine app/web.1:   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 145, in _send_event 
Apr 03 14:39:22 trestle-shrine app/web.1:     raise ValueError("Unexpected status code: %s" % response.status) 
Apr 03 14:39:22 trestle-shrine app/web.1: ValueError: Unexpected status code: 403 `

**Comment by untitaker** [comment] 2019-04-03 21:44
Okay, I will release a version of the SDK that also logs the server's response body. I believe the event payload is getting too big.

**Comment by reparadocs** [comment] 2019-04-03 21:53
I think the problem is Sentry is somehow receiving a 403 from somewhere - the actual response from the server is a 500 error :/

**Comment by untitaker** [comment] 2019-04-03 21:54
Yes, the 403 I am talking about occurs when the SDK sends the error to Sentry. Sentry responds with a 403, and I believe this is because the error payload is too big.

**Comment by untitaker** [comment] 2019-04-03 21:54
I will release a new version soon.

**Comment by reparadocs** [comment] 2019-04-03 21:55
Ah ok - appreciate it!

**Comment by untitaker** [comment] 2019-04-05 23:48
@reparadocs could you upgrade to 0.7.10 and check the debug log again?

**Comment by reparadocs** [comment] 2019-04-07 04:21
Unfortunately, same error even after upgrading:

```
[sentry] ERROR: Internal error in sentry_sdk 
Apr 06 21:20:44 trestle-shrine app/web.1:  Traceback (most recent call last): 
Apr 06 21:20:44 trestle-shrine app/web.1:    File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 43, in capture_internal_exceptions 
Apr 06 21:20:44 trestle-shrine app/web.1:      yield 
Apr 06 21:20:44 trestle-shrine app/web.1:    File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 157, in send_event_wrapper 
Apr 06 21:20:44 trestle-shrine app/web.1:      self._send_event(event) 
Apr 06 21:20:44 trestle-shrine app/web.1:    File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 145, in _send_event 
Apr 06 21:20:44 trestle-shrine app/web.1:      raise ValueError("Unexpected status code: %s" % response.status) 
Apr 06 21:20:44 trestle-shrine app/web.1:  ValueError: Unexpected status code: 403 
Apr 06 21:20:44 trestle-shrine app/web.1:  ERROR:sentry_sdk.errors:Internal error in sentry_sdk 
Apr 06 21:20:44 trestle-shrine app/web.1:  Traceback (most recent call last): 
Apr 06 21:20:44 trestle-shrine app/web.1:    File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 43, in capture_internal_exceptions 
Apr 06 21:20:44 trestle-shrine app/web.1:      yield 
Apr 06 21:20:44 trestle-shrine app/web.1:    File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 157, in send_event_wrapper 
Apr 06 21:20:44 trestle-shrine app/web.1:      self._send_event(event) 
Apr 06 21:20:44 trestle-shrine app/web.1:    File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/transport.py", line 145, in _send_event 
Apr 06 21:20:44 trestle-shrine app/web.1:      raise ValueError("Unexpected status code: %s" % response.status) 
Apr 06 21:20:44 trestle-shrine app/web.1:  ValueError: Unexpected status code: 403 
```

**Comment by reparadocs** [comment] 2019-04-07 04:30
Once I upgraded, I now get this error:

```
Apr 06 21:27:07 trestle-shrine app/web.1:  [sentry] ERROR: Unexpected status code: 403 (body: b'{"error":"Event dropped due to filter: web-crawlers"}') 
Apr 06 21:27:07 trestle-shrine app/web.1: ERROR:sentry_sdk.errors:Unexpected status code: 403 (body: b'{"error":"Event dropped due to filter: web-crawlers"}') 
```

Is the slack webhook being miscategorized as a web crawler? Is there a way to disable this filter?.

**Comment by untitaker** [comment] 2019-04-07 16:45
Ah! Go to your project settings, go to "Inbound Filters". There you will see the option for "known web-crawlers" likely enabled:

<img width="577" alt="Screenshot 2019-04-07 at 18 43 25" src="https://user-images.githubusercontent.com/837573/55686725-1fb47580-5965-11e9-9982-41da3b2e5774.png">

We maintain a regex for those user agents here: https://github.com/getsentry/sentry/blob/e6cc8483b3992fb02ebb39649efd2b264fcadeca/src/sentry/filters/web_crawlers.py#L38-L39

If you want to refine that regex somehow feel free to open a PR.

I will close this though since it's not a bug in the SDK. Thanks for responding so quickly!

**Closed** 2019-04-07 16:45 UTC
Labels: needs-information
