### ISSUE TITLE
Number limit on extra items set by set_extra()?

### ISSUE THREAD

**Issue by laggardkernel** [getsentry/sentry-python#595] opened 2020-01-20 10:33 UTC
Is there any limit on the number of extra info set by `set_extra`? With the following test, I can only see 10 items under the "ADDITIONAL DATA" section on the monitor page.

```python
            with push_scope() as scope:
                for _ in range(100):
                    scope.set_extra(_, _)
                capture_exception(e)

```

Sentry is running in docker, with version "Sentry 10.1.0.dev0 (2232401f0acc359baeaf186ee3e125c71cb38cdd)".

sentry-sdk, 0.14.0.

**Comment by untitaker** [comment] 2020-01-21 17:09
Hi, this is a duplicate of #377, thanks!

**Closed by untitaker** 2020-01-21 17:09 UTC
