### ISSUE TITLE
First exception not flushed on Celery+Python until second occurrence

### ISSUE THREAD

**Issue by nicolasgrasset** [getsentry/sentry-python#687] opened 2020-05-13 15:38 UTC
Here is an issue that's a little hard to understand. We run Sentry on Django+Celery.

```
Django==2.2.12
celery==4.4.2
sentry-sdk==0.14.3
```

We run many packages on that project, so I suspect it's a conflict with another one but I do not know where to start.

### Details

1. Exceptions are reported to Sentry as expected on the Django wsgi
2. Exceptions from code running on Celery will not be reported immediately
3. Triggering the same exception (same fingerprint, different message) a second time will "flush" both  and they will both appear on Sentry
4. Triggering 2 different exceptions on a single Celery task will not report either of them to Sentry
5. Calling `Hub.current.client.flush()` doesn't change any of it

### Celery task

```python
@app.task
def sentry_logging_task(what):
    try:
        raise Exception("Sentry say what? {}".format(what))
    except Exception as e:
        logger.exception(str(e))
```

### Sentry init

```python
sentry_sdk.init(
    dsn=settings.DNS,
    integrations=[DjangoIntegration(), CeleryIntegration()],
    environment=settings.ENV
 )
 ignore_logger('django.security.DisallowedHost')
```

**Comment by untitaker** [comment] 2020-05-15 19:32
How are you launching the celery workers? Is there anything special about the way you are configuring celery?

**Comment by fellowshipofone** [comment] 2020-05-15 20:11
Thanks for the follow up @untitaker:

Nothing special. I can reproduce the issue 100% of the time locally and I launch it with `pipenv` so it loads a .env file as environment variables
```
pipenv run celery worker -A app -n app
```

On production it runs in a docker container.

**Comment by RobbieClarken** [comment] 2021-08-04 09:28
I've confirmed that the bug can still be reproduced with the steps outlined above with the latest release of sentry-sdk (v1.3.1).

<details>
<summary>logs</summary>

```
[2021-08-04 18:48:04,389: INFO/MainProcess] Scaling down 1 processes.
[2021-08-04 18:48:04,391: DEBUG/ForkPoolWorker-1] Flushing HTTP transport
[2021-08-04 18:48:04,392: DEBUG/ForkPoolWorker-1] background worker got flush request
[2021-08-04 18:48:04,494: DEBUG/ForkPoolWorker-1] 2 event(s) pending on flush
[2021-08-04 18:48:06,395: ERROR/ForkPoolWorker-1] flush timed out, dropped 2 events
[2021-08-04 18:48:06,396: DEBUG/ForkPoolWorker-1] background worker flushed
```

</details>

@untitaker Would you mind removing the `needs-information` and `question` labels from this issue?

**Comment by RobbieClarken** [comment] 2021-12-26 05:57
I've confirmed that this bug is still present in sentry-sdk 1.5.1 and master although the behaviour has changed due to commit a6cc9718fe398acee134e6ee9297e0fddea9b359.

There is still the issue that the first logged error doesn't get processed immediately and could stay pending on the queue indefinitely. However: 
- Prior to a6cc9718fe398acee134e6ee9297e0fddea9b359 when the Celery worker was terminated the pending event would be dropped and never reported.
- From a6cc9718fe398acee134e6ee9297e0fddea9b359 onwards when the Celery worker is terminated the pending event does get reported to Sentry.

I still consider this an issue because the Celery worker may not be terminated for quite some time and so the error may not be reported until it is too late.

The code in https://github.com/getsentry/sentry-python/issues/687#issuecomment-837738001 can still be used to replicate the issue. By default Celery autoscales down inactive workers after 30 seconds so the error will be reported after 30 seconds. This can be changed with the [`AUTOSCALE_KEEPALIVE`](https://github.com/celery/celery/blob/527458d8d419cb41b74c5b05aaa8ddf957704f84/celery/worker/autoscale.py#L28) environment variable. For example, setting `AUTOSCALE_KEEPALIVE=600` will demonstrate the error doesn't get reported for 10 minutes.

**Comment by antonpirker** [comment] 2023-11-14 14:10
Hey @nicolasgrasset and @RobbieClarken 

Better late than never. I just tried to reproduce this with Sentry SDK version 1.35.0, Python 3.9.15, celery 5.3.5 and redis as the Celery broker. Redis server version 7.2.1

I used this `tasks.py` file:
```
# tasks.py
import os 
import logging
import time
from secrets import token_hex

from celery import Celery
import sentry_sdk


sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    enable_tracing=True,
    debug=True,
    send_default_pii=True,
)

app = Celery("tasks", broker='redis://localhost:6379/0')
logger = logging.getLogger(__name__)

logger.error(f"SETUP {token_hex(2)}")

@app.task
def my_task():
    logger.error(f"MY_TASK2 {token_hex(2)}")
    time.sleep(1)
```

This is how I run celery:
```
celery -A tasks.app worker \
    --loglevel=INFO \
    --autoscale 4,0
```

And this is how I tall the task:
```
python -c 'import tasks; tasks.my_task.delay()'
```

This is the output of Celery I get:
```
[2023-11-14 15:03:24,218: INFO/MainProcess] Task tasks.my_task[c3877e25-ce4f-44ae-9917-ab4477ceb57a] received
[2023-11-14 15:03:24,218: INFO/MainProcess] Scaling up 1 processes.
[2023-11-14 15:03:24,241: DEBUG/ForkPoolWorker-1] [Tracing] Extracted propagation context from incoming data: {'trace_id': '60298be3580046bcb81e55784f1a87c2', 'parent_span_id': 'be2335eb4aead2ff', 'parent_sampled': None, 'span_id': '9c00cc87ad85d6f9'}
[2023-11-14 15:03:24,242: DEBUG/ForkPoolWorker-1] [Tracing] Starting <queue.task.celery> transaction <tasks.my_task>
[2023-11-14 15:03:24,242: DEBUG/ForkPoolWorker-1] [Profiling] Discarding profile because profiler was not started.
[2023-11-14 15:03:24,242: ERROR/ForkPoolWorker-1] MY_TASK2 709d
[2023-11-14 15:03:25,247: INFO/ForkPoolWorker-1] Task tasks.my_task[c3877e25-ce4f-44ae-9917-ab4477ceb57a] succeeded in 1.0041934169999998s: None
[2023-11-14 15:03:25,252: DEBUG/ForkPoolWorker-1] Sending envelope [envelope with 1 items (error)] project:5461230 host:o447951.ingest.sentry.io
[2023-11-14 15:03:25,287: DEBUG/ForkPoolWorker-1] Sending envelope [envelope with 1 items (transaction)] project:5461230 host:o447951.ingest.sentry.io
[2023-11-14 15:04:00,809: INFO/MainProcess] Scaling down 1 processes.
[2023-11-14 15:04:00,819: DEBUG/ForkPoolWorker-1] Flushing HTTP transport
[2023-11-14 15:04:00,822: DEBUG/ForkPoolWorker-1] background worker got flush request
```

So immediately after the my_task is finished the error (and one transaction event) is sent to Sentry.

I am not able to reproduce this behavior.

As this is a quiet old issue, could you please check if the issue has been resolved as of now, or if it is still occurring!
Many thanks and sorry again for the late answer.

**Comment by RobbieClarken** [comment] 2023-11-14 22:56
@antonpirker Yes, I can still reproduce the issue including with the dependencies you specified. However if I include `enable_tracing=True` in the `sentry_sdk.init()` I don't get the problem.

Could you please try reproducing without the `enable_tracing=True` line in `tasks.py`?

## Logs

<details>
<summary>versions</summary>

```
$ .venv/bin/python --version
Python 3.9.15

$ .venv/bin/pip freeze
amqp==5.2.0
async-timeout==4.0.3
billiard==4.2.0
celery==5.3.5
certifi==2023.7.22
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
kombu==5.3.3
prompt-toolkit==3.0.41
python-dateutil==2.8.2
redis==5.0.1
sentry-sdk==1.35.0
six==1.16.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.1.0
vine==5.1.0
wcwidth==0.2.10

$ redis-server --version
Redis server v=7.2.3 sha=00000000:0 malloc=libc bits=64 build=96f23777753ded6c
```

</details>

<details>
<summary><code>tasks.py</code></summary>

```python
import os
import logging
import time
from secrets import token_hex

from celery import Celery
import sentry_sdk


sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    enable_tracing=True,  # this changes the behaviour
    debug=True,
    send_default_pii=True,
)

app = Celery("tasks", broker='redis://localhost:6379/0')
logger = logging.getLogger(__name__)

logger.error(f"SETUP {token_hex(2)}")

@app.task
def my_task():
    logger.error(f"MY_TASK2 {token_hex(2)}")
    time.sleep(1)
```

</details>

<details>
<summary>log without <code>enable_tracing=True</code></summary>

```
$ .venv/bin/celery -A tasks.app worker --loglevel=INFO --autoscale 4,0
 [sentry] DEBUG: Setting up integrations (with default = True)
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.aiohttp.AioHttpIntegration: AIOHTTP not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.boto3.Boto3Integration: botocore is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.bottle.BottleIntegration: Bottle not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.django.DjangoIntegration: Django not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.falcon.FalconIntegration: Falcon not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.fastapi.FastApiIntegration: Starlette is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.flask.FlaskIntegration: Flask is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.httpx.HttpxIntegration: httpx is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.pyramid.PyramidIntegration: Pyramid not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.rq.RqIntegration: RQ not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sanic.SanicIntegration: Sanic not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sqlalchemy.SqlalchemyIntegration: SQLAlchemy not installed.
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.starlette.StarletteIntegration: Starlette is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.tornado.TornadoIntegration: Tornado not installed
 [sentry] DEBUG: Setting up previously not enabled integration argv
 [sentry] DEBUG: Setting up previously not enabled integration atexit
 [sentry] DEBUG: Setting up previously not enabled integration dedupe
 [sentry] DEBUG: Setting up previously not enabled integration excepthook
 [sentry] DEBUG: Setting up previously not enabled integration logging
 [sentry] DEBUG: Setting up previously not enabled integration modules
 [sentry] DEBUG: Setting up previously not enabled integration stdlib
 [sentry] DEBUG: Setting up previously not enabled integration threading
 [sentry] DEBUG: Setting up previously not enabled integration celery
 [sentry] DEBUG: Setting up previously not enabled integration redis
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration threading
 [sentry] DEBUG: Enabling integration celery
 [sentry] DEBUG: Enabling integration redis
 [sentry] DEBUG: Setting SDK name to 'sentry.python'
SETUP 7642
 [sentry] DEBUG: Sending event, type:null level:error event_id:1f40a7ab9b9348c98eacaf0b7d4d037a project:4506226358157312 host:o1412735.ingest.sentry.io

celery@noether v5.3.5 (emerald-rush)

macOS-12.5.1-arm64-64bit 2023-11-15 09:12:20

[config]
.> app:         tasks:0x10458f580
.> transport:   redis://localhost:6379/0
.> results:     disabled://
.> concurrency: {min=0, max=4} (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery

[tasks]
  . tasks.my_task

[2023-11-15 09:12:20,956: WARNING/MainProcess] /Users/robbie/Developer/scratch/sentry-issue/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-11-15 09:12:20,959: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-11-15 09:12:20,960: WARNING/MainProcess] /Users/robbie/Developer/scratch/sentry-issue/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-11-15 09:12:20,961: INFO/MainProcess] mingle: searching for neighbors
[2023-11-15 09:12:21,970: INFO/MainProcess] mingle: all alone
[2023-11-15 09:12:21,986: INFO/MainProcess] celery@noether ready.
[2023-11-15 09:12:27,422: INFO/MainProcess] Task tasks.my_task[66843bc3-8186-42e2-8d03-c9e5febf60cb] received
[2023-11-15 09:12:27,422: INFO/MainProcess] Scaling up 1 processes.
 [sentry] DEBUG: [Tracing] Extracted propagation context from incoming data: {'dynamic_sampling_context': {'trace_id': 'bf59073d09ee4cbf928adcaddef40d03', 'environment': 'production', 'release': '0e22824e4e5ed5855a12e155a0398a1abe38f107', 'public_key': '183bf1a5cbdb1045cacdf2251e1d0ddc'}, 'trace_id': 'bf59073d09ee4cbf928adcaddef40d03', 'parent_span_id': 'bf9dee129daa6582', 'parent_sampled': None, 'span_id': '901b482e718b2401'}
[2023-11-15 09:12:27,458: DEBUG/ForkPoolWorker-1] [Tracing] Extracted propagation context from incoming data: {'dynamic_sampling_context': {'trace_id': 'bf59073d09ee4cbf928adcaddef40d03', 'environment': 'production', 'release': '0e22824e4e5ed5855a12e155a0398a1abe38f107', 'public_key': '183bf1a5cbdb1045cacdf2251e1d0ddc'}, 'trace_id': 'bf59073d09ee4cbf928adcaddef40d03', 'parent_span_id': 'bf9dee129daa6582', 'parent_sampled': None, 'span_id': '901b482e718b2401'}
 [sentry] DEBUG: [Profiling] Discarding profile because transaction is discarded.
[2023-11-15 09:12:27,459: DEBUG/ForkPoolWorker-1] [Profiling] Discarding profile because transaction is discarded.
[2023-11-15 09:12:27,459: ERROR/ForkPoolWorker-1] MY_TASK2 f01d
[2023-11-15 09:12:28,462: INFO/ForkPoolWorker-1] Task tasks.my_task[66843bc3-8186-42e2-8d03-c9e5febf60cb] succeeded in 1.0028278329999996s: None
 [sentry] DEBUG: Discarding transaction because sampled = False
[2023-11-15 09:12:28,464: DEBUG/ForkPoolWorker-1] Discarding transaction because sampled = False



^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 [sentry] DEBUG: Flushing HTTP transport
[2023-11-15 09:12:38,671: DEBUG/ForkPoolWorker-1] Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
[2023-11-15 09:12:38,672: DEBUG/ForkPoolWorker-1] background worker got flush request
 [sentry] DEBUG: Sending event, type:null level:error event_id:ac881e2b06c142509c948712e0352186 project:4506226358157312 host:o1412735.ingest.sentry.io
[2023-11-15 09:12:38,672: DEBUG/ForkPoolWorker-1] Sending event, type:null level:error event_id:ac881e2b06c142509c948712e0352186 project:4506226358157312 host:o1412735.ingest.sentry.io
 [sentry] DEBUG: background worker flushed
[2023-11-15 09:12:38,706: DEBUG/ForkPoolWorker-1] background worker flushed
 [sentry] DEBUG: atexit: got shutdown signal
[2023-11-15 09:12:40,220: DEBUG/MainProcess] atexit: got shutdown signal
 [sentry] DEBUG: atexit: shutting down client
[2023-11-15 09:12:40,221: DEBUG/MainProcess] atexit: shutting down client
 [sentry] DEBUG: Flushing HTTP transport
[2023-11-15 09:12:40,221: DEBUG/MainProcess] Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
[2023-11-15 09:12:40,221: DEBUG/MainProcess] background worker got flush request
 [sentry] DEBUG: background worker flushed
[2023-11-15 09:12:40,222: DEBUG/MainProcess] background worker flushed
 [sentry] DEBUG: Killing HTTP transport
[2023-11-15 09:12:40,222: DEBUG/MainProcess] Killing HTTP transport
 [sentry] DEBUG: background worker got kill request
[2023-11-15 09:12:40,222: DEBUG/MainProcess] background worker got kill request
```

</details>

<details>
<summary>log with <code>enable_tracing=True</code></summary>

```
09:14 (1) $ .venv/bin/celery -A tasks.app worker --loglevel=INFO --autoscale 4,0
 [sentry] DEBUG: Setting up integrations (with default = True)
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.aiohttp.AioHttpIntegration: AIOHTTP not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.boto3.Boto3Integration: botocore is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.bottle.BottleIntegration: Bottle not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.django.DjangoIntegration: Django not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.falcon.FalconIntegration: Falcon not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.fastapi.FastApiIntegration: Starlette is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.flask.FlaskIntegration: Flask is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.httpx.HttpxIntegration: httpx is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.pyramid.PyramidIntegration: Pyramid not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.rq.RqIntegration: RQ not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sanic.SanicIntegration: Sanic not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sqlalchemy.SqlalchemyIntegration: SQLAlchemy not installed.
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.starlette.StarletteIntegration: Starlette is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.tornado.TornadoIntegration: Tornado not installed
 [sentry] DEBUG: Setting up previously not enabled integration argv
 [sentry] DEBUG: Setting up previously not enabled integration atexit
 [sentry] DEBUG: Setting up previously not enabled integration dedupe
 [sentry] DEBUG: Setting up previously not enabled integration excepthook
 [sentry] DEBUG: Setting up previously not enabled integration logging
 [sentry] DEBUG: Setting up previously not enabled integration modules
 [sentry] DEBUG: Setting up previously not enabled integration stdlib
 [sentry] DEBUG: Setting up previously not enabled integration threading
 [sentry] DEBUG: Setting up previously not enabled integration celery
 [sentry] DEBUG: Setting up previously not enabled integration redis
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration threading
 [sentry] DEBUG: Enabling integration celery
 [sentry] DEBUG: Enabling integration redis
 [sentry] DEBUG: Setting SDK name to 'sentry.python'
SETUP 38b1
 [sentry] DEBUG: Sending envelope [envelope with 1 items (error)] project:4506226358157312 host:o1412735.ingest.sentry.io

celery@noether v5.3.5 (emerald-rush)

macOS-12.5.1-arm64-64bit 2023-11-15 09:14:32

[config]
.> app:         tasks:0x1062e3580
.> transport:   redis://localhost:6379/0
.> results:     disabled://
.> concurrency: {min=0, max=4} (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery

[tasks]
  . tasks.my_task

[2023-11-15 09:14:32,987: WARNING/MainProcess] /Users/robbie/Developer/scratch/sentry-issue/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-11-15 09:14:32,992: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-11-15 09:14:32,992: WARNING/MainProcess] /Users/robbie/Developer/scratch/sentry-issue/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-11-15 09:14:32,995: INFO/MainProcess] mingle: searching for neighbors
[2023-11-15 09:14:34,004: INFO/MainProcess] mingle: all alone
[2023-11-15 09:14:34,021: INFO/MainProcess] celery@noether ready.
[2023-11-15 09:14:38,430: INFO/MainProcess] Task tasks.my_task[fc248b87-4b32-446b-96ce-ff9b073eb67d] received
[2023-11-15 09:14:38,430: INFO/MainProcess] Scaling up 1 processes.
 [sentry] DEBUG: [Tracing] Extracted propagation context from incoming data: {'trace_id': 'a59631e7c4d44897a71f93547aa23fb0', 'parent_span_id': '8665693329723f90', 'parent_sampled': None, 'span_id': 'bc1aca9d0bba7130'}
[2023-11-15 09:14:38,470: DEBUG/ForkPoolWorker-1] [Tracing] Extracted propagation context from incoming data: {'trace_id': 'a59631e7c4d44897a71f93547aa23fb0', 'parent_span_id': '8665693329723f90', 'parent_sampled': None, 'span_id': 'bc1aca9d0bba7130'}
 [sentry] DEBUG: [Tracing] Starting <queue.task.celery> transaction <tasks.my_task>
[2023-11-15 09:14:38,470: DEBUG/ForkPoolWorker-1] [Tracing] Starting <queue.task.celery> transaction <tasks.my_task>
 [sentry] DEBUG: [Profiling] Discarding profile because profiler was not started.
[2023-11-15 09:14:38,471: DEBUG/ForkPoolWorker-1] [Profiling] Discarding profile because profiler was not started.
[2023-11-15 09:14:38,471: ERROR/ForkPoolWorker-1] MY_TASK2 1469
[2023-11-15 09:14:39,473: INFO/ForkPoolWorker-1] Task tasks.my_task[fc248b87-4b32-446b-96ce-ff9b073eb67d] succeeded in 1.0021337079999997s: None
 [sentry] DEBUG: Sending envelope [envelope with 1 items (error)] project:4506226358157312 host:o1412735.ingest.sentry.io
[2023-11-15 09:14:39,479: DEBUG/ForkPoolWorker-1] Sending envelope [envelope with 1 items (error)] project:4506226358157312 host:o1412735.ingest.sentry.io
 [sentry] DEBUG: Sending envelope [envelope with 1 items (transaction)] project:4506226358157312 host:o1412735.ingest.sentry.io
[2023-11-15 09:14:39,519: DEBUG/ForkPoolWorker-1] Sending envelope [envelope with 1 items (transaction)] project:4506226358157312 host:o1412735.ingest.sentry.io





^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 [sentry] DEBUG: Flushing HTTP transport
[2023-11-15 09:14:47,642: DEBUG/ForkPoolWorker-1] Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
[2023-11-15 09:14:47,642: DEBUG/ForkPoolWorker-1] background worker got flush request
 [sentry] DEBUG: background worker flushed
[2023-11-15 09:14:47,643: DEBUG/ForkPoolWorker-1] background worker flushed
 [sentry] DEBUG: atexit: got shutdown signal
[2023-11-15 09:14:49,159: DEBUG/MainProcess] atexit: got shutdown signal
 [sentry] DEBUG: atexit: shutting down client
[2023-11-15 09:14:49,159: DEBUG/MainProcess] atexit: shutting down client
 [sentry] DEBUG: Flushing HTTP transport
[2023-11-15 09:14:49,159: DEBUG/MainProcess] Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
[2023-11-15 09:14:49,160: DEBUG/MainProcess] background worker got flush request
 [sentry] DEBUG: background worker flushed
[2023-11-15 09:14:49,160: DEBUG/MainProcess] background worker flushed
 [sentry] DEBUG: Killing HTTP transport
[2023-11-15 09:14:49,160: DEBUG/MainProcess] Killing HTTP transport
 [sentry] DEBUG: background worker got kill request
[2023-11-15 09:14:49,160: DEBUG/MainProcess] background worker got kill request
```

</details>

**Comment by antonpirker** [comment] 2023-11-16 07:44
Thanks for the update. Yes, will try with `enable_tracing=False` (same thing as omitting it)

**Comment by szokeasaurusrex** [comment] 2024-04-15 16:35
Hi @RobbieClarken, I attempted to reproduce the issue using the instructions you provided. My reproduction is available [here](https://github.com/szokeasaurusrex/issue-reproductions/tree/main/getsentry/sentry-python/687).

It indeed appears that there is a delay in sending the error event; however, in my testing, it appeared that the event still got sent eventually, either after a delay of approximately a few minutes or after interrupting the Celery worker with Ctrl-C.

Does this match the behavior you are observing?

**Comment by RobbieClarken** [comment] 2024-05-08 01:23
> It indeed appears that there is a delay in sending the error event; however, in my testing, it appeared that the event still got sent eventually, either after a delay of approximately a few minutes or after interrupting the Celery worker with Ctrl-C.

@szokeasaurusrex I'm seeing the same behaviour when I install the latest sentry-sdk (v2.1.1).

The behaviour looks to have changed in sentry-sdk v1.4.0; prior to this version (eg v1.3.1) when the Celery worker was scaled down (after ~60 seconds of inactivity) we would see:

```
[2024-05-08 10:25:54,242: INFO/MainProcess] Scaling down 1 processes.
[2024-05-08 10:25:54,247: DEBUG/ForkPoolWorker-1] Flushing HTTP transport
[2024-05-08 10:25:54,249: DEBUG/ForkPoolWorker-1] background worker got flush request
[2024-05-08 10:25:54,352: DEBUG/ForkPoolWorker-1] 2 event(s) pending on flush
[2024-05-08 10:25:56,254: ERROR/ForkPoolWorker-1] flush timed out, dropped 2 events
[2024-05-08 10:25:56,256: DEBUG/ForkPoolWorker-1] background worker flushed
```

From sentry-sdk v1.4.0 onwards we see:

```
[2024-05-08 10:24:30,125: INFO/MainProcess] Scaling down 1 processes.
[2024-05-08 10:24:30,141: DEBUG/ForkPoolWorker-1] Flushing HTTP transport
[2024-05-08 10:24:30,142: DEBUG/ForkPoolWorker-1] background worker got flush request
[2024-05-08 10:24:30,143: DEBUG/ForkPoolWorker-1] Sending event, type:null level:error event_id:389743b4dd5b415b81f6241aa55bf471 project:4506505340846080 host:o1412735.ingest.sentry.io
[2024-05-08 10:24:30,144: DEBUG/ForkPoolWorker-1] [Tracing] Adding `sentry-trace` header 8b973f65f8c446a0a7a5c899926a295a-a1e9de2c17787839- to outgoing request to https://o1412735.ingest.sentry.io/api/4506505340846080/store/.
[2024-05-08 10:24:30,180: DEBUG/ForkPoolWorker-1] background worker flushed
```

So it seems that the errors will now be eventually reported... it may just be after ~60 second delay.

**Comment by szokeasaurusrex** [comment] 2024-05-08 09:41
> So it seems that the errors will now be eventually reported... it may just be after ~60 second delay.

@RobbieClarken So, if I am understanding you correctly, it sounds like this issue has now been resolved. Is that correct? Or, is there still some problem we need to address before we close this issue?

**Comment by RobbieClarken** [comment] 2024-05-08 11:25
@szokeasaurusrex IMO the fact the error doesn't get reported until the celery worker is scaled down is an indication there is still a bug in sentry-sdk since errors should be reported immediately. I'm not sure if there is any situation where the worker will never get scaled down (which would mean the error would never be reported) or whether the bug can present itself in other ways.

That said, it may be that the current behaviour could be considered acceptable. With the default celery autoscaling configuration I doubt anyone would notice the delay in the error reporting.

**Comment by sl0thentr0py** [comment] 2024-05-08 14:28
@RobbieClarken adding some more info here because I just tried this out.

In general, we've been telling celery users to use the `celeryd_init` or `worker_init` signals to init sentry instead of like you do in your sample.

```python
@signals.celeryd_init.connect
# @signals.worker_init.connect
def init_worker(**_kwargs):
    init_sentry()
```

With the signal init, I can see the error events sent immediately while with the module level init, there does seem to be a consistent delay. 

I don't know the root cause (would need to dig into the celery worker / threading condition mess) but maybe this helps for other people looking at this issue.

**Comment by RobbieClarken** [comment] 2024-05-30 08:27
Thanks @sl0thentr0py - I can confirm with the code below the errors are reported immediately. Given this recommended setup is explained in the docs I think this issue can be closed.

<details><summary><code>tasks.py</code></summary>

```python
import logging
import time
from secrets import token_hex

from celery import Celery, signals
import sentry_sdk

def sentry_init():
    sentry_sdk.init(dsn="CHANGE_ME", debug=True)

sentry_init()
app = Celery(backend="rpc://")
logger = logging.getLogger(__name__)

logger.error(f"SETUP {token_hex(2)}")

@signals.celeryd_init.connect
def init_worker(**_kwargs):
    sentry_init()

@app.task
def my_task():
    logger.error(f"MY_TASK {token_hex(2)}")
    time.sleep(1)
```

</details>

**Closed** 2024-05-31 12:12 UTC
Labels: Type: Bug, Integration: Celery, Waiting for: Product Owner, triaged
